### ISSUE TITLE
Can see a bit of my desktop though hyprlock

### ISSUE THREAD

**Issue by DHDcc** [hyprwm/hyprlock#461]
### Regression?

No

### Hyprlock Info and Version

hyprlock v0.4.1-1
<details> <summary>Hyprlock config</summary>

```sh
# GENERAL
general {
  no_fade_in = false
  grace = 0
  disable_loading_bar = false
  hide_cursor = true
  ignore_empty_input = true
  text_trim = true
}

#BACKGROUND
background {
    monitor =
    path = $HOME/.config/swww/wallpapers/abstract.png
    blur_size = 2
    blur_passes = 3 # 0 disables blurring
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# TIME HR
label {
    monitor =
    text = cmd[update:1000] date +"%H"
    color = rgba(255, 255, 255, 1)
    #shadow_pass = 2
    shadow_size = 3
    shadow_color = rgb(0,0,0)
    shadow_boost = 1.2
    font_size = 200
    font_family = AlfaSlabOne
    position = 0, -270
    halign = center
    valign = top
}

# TIME
label {
    monitor =
    text = cmd[update:1000] date +"%M"
    color = rgba(255, 255, 255, 1)
    font_size = 200
    font_family = AlfaSlabOne
    position = 0, -500
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:1000] date +"%d %b %A"
    color = rgba(255, 255, 255, 1)
    font_size = 17
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 10, -115
    halign = center
    valign = center
}

# LOCATION & WEATHER
label {
    monitor =
    text = cmd[update:1000] ~/.scripts/weather.sh
    color = rgba(255, 255, 255, 1)
    font_size = 17
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, 665
    halign = center
    valign = center
}

# Music Background
#shape {
#    monitor =
#    size = 420, 90
#    rounding = 10
#    border_size = 1
#    color =  rgba(0,0,0,1)
#    border_color =  rgba(249,249,249,1)
#    rotate = 0
#    shadow_passes = 2
#    shadow_size = 4
#    position = 20, -309
#    halign = center
#    valign = center
#    zindex = 0
#}

image {
    monitor =
    path =
    size = 75 # lesser side if not 1:1 ratio
    rounding = 5 # negative values mean circle
    border_size = 0
    rotate = 0 # degrees, counter-clockwise
    reload_time = 2
    reload_cmd = ~/.scripts/playerctlock.sh --arturl
    position = -195, -365
    halign = center
    valign = center
    #opacity=0.5
}

# PLAYER TITTLE
label {
    monitor =
    text = cmd[update:0] ~/.scripts/playerctlock.sh --title
    color = rgba(255, 255, 255, 0.8)
    font_size = 16
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 1165, -345
    halign = left
    valign = center
}

# PLAYER Length
label {
    monitor =
    text = cmd[update:0] ~/.scripts/playerctlock.sh --duration
    color = rgba(255, 255, 255, 1)
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono
    position = -1020, -370
    halign = right
    valign = center
}

# PLAYER STATUS
label {
    monitor =
    text = cmd[update:0] ~/.scripts/playerctlock.sh --status
    color = rgba(255, 255, 255, 1)
    font_size = 18
    font_family = JetBrains Mono Nerd Font Mono
    position = -1020, -345
    halign = right
    valign = center
}
# PLAYER SOURCE
label {
    monitor =
    text = cmd[update:0] ~/.scripts/playerctlock.sh --source
    color = rgba(255, 255, 255, 0.6)
    font_size = 11
    font_family = JetBrains Mono Nerd Font Mono
    position = -1020 -395
    halign = right
    valign = center
}

# PLAYER Artist
label {
    monitor =
    text = cmd[update:0] ~/.scripts/playerctlock.sh --artist
    color = rgba(255, 255, 255, 0.8)
    font_size = 12
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 1165, -370
    halign = left
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 350, 75
    outline_thickness = 3
    outer_color = rgba(0, 0, 0, 1)
    dots_size = 0.1 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 1 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    inner_color = rgba(0, 0, 0, 1)
    font_color = rgba(200, 200, 200, 1)
    fade_on_empty = false
    #font_family = JetBrains Mono Nerd Font Mono
    placeholder_text = <span foreground="##cdd6f4">   $USER</span>
    hide_input = false
    position = 4, -640
    halign = center
    rounding = 10
    valign = center
    zindex = 10
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: ArchBox
Release: 6.10.4-arch2-1
Version: #1 SMP PREEMPT_DYNAMIC Sun, 11 Aug 2024 16:19:06 +0000


GPU information:
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] [1002:731f] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

When I switch from a 24" to a 27" monitor, I noticed that I could see a bit of my desktop on the right of my monitor
 when I use hyprlock.

### How to reproduce

Use hyprlock on a 27" monitor.

### Crash reports, logs, images, videos

![swappy-20240815-192811](https://github.com/user-attachments/assets/c6f5baf7-c17c-446b-b79b-0d67c5cdba29)

**Comment by DHDcc** [comment]
> Well I seem to have the same behavior, and it's when the image is too small for the screen (at least for me), when I use an image which is much too small I can see my desktop clearly and without any blur.

Can it simply stretch the image to fit the monitor size?

**Comment by floork** [comment]
Well if you only use 1 wallpaper you could add `size` to the image and scale it up see the [wiki](https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#image), but it would be optimal if hyprlock would implement something that when an image is too small to also have the option to hide the rest in blur, or even better with the color tag over the rest of the screen.

**Comment by DHDcc** [comment]
> Well if you only use 1 wallpaper you could add `size` to the image and scale it up see the [wiki](https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#image), but it would be optimal if hyprlock would implement something that when an image is too small to also have the option to hide the rest in blur, or even better with the color tag over the rest of the screen.

The ```size``` option is only for the ```image``` section and not for the ```background``` section.

**Comment by floork** [comment]
Sorry my bad, well as of now I don't really see any way to adjust the size in the lock screen.

**Comment by AndreasBackx** [comment]
I'm actually getting this even when solely using a black colour, not an image:

```
background {
    monitor =
    color = rgba(0, 0, 0, 1.0)
}
```

I have 3 displays in the order portrait, landscape, portrait. On my leftmost one, I can see about 30% of what is "behind" the lock screen still.

Full `hyprctl monitors` output:
```
Monitor HDMI-A-1 (ID 1):
	2560x1440@59.95100 at 5168x226
	description: Dell Inc. DELL U2515H 9X2VY6A80A8L
	make: Dell Inc.
	model: DELL U2515H
	serial: 9X2VY6A80A8L
	active workspace: 201 (201)
	special workspace: 0 ()
	reserved: 0 0 0 40
	scale: 1.00
	transform: 3
	focused: no
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 2560x1440@59.95Hz 2048x1152@60.00Hz 1920x1200@59.95Hz 1920x1080@60.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1920x1080@30.00Hz 1920x1080@29.97Hz 1920x1080@25.00Hz 1920x1080@24.00Hz 1920x1080@23.98Hz 1600x1200@60.00Hz 1680x1050@59.88Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1440x900@59.95Hz 1200x960@59.99Hz 1280x800@59.95Hz 1152x864@75.00Hz 1280x720@60.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@75.03Hz 1024x768@60.00Hz 800x600@75.00Hz 800x600@60.32Hz 720x576@50.00Hz 720x480@60.00Hz 720x480@60.00Hz 720x480@59.94Hz 720x480@59.94Hz 720x480@59.94Hz 640x480@75.00Hz 640x480@60.00Hz 640x480@59.94Hz 640x480@59.94Hz 720x400@70.08Hz

Monitor DP-8 (ID 4):
	3840x2160@59.99700 at 0x0
	description: Dell Inc. DELL U3219Q F2XWXV2
	make: Dell Inc.
	model: DELL U3219Q
	serial: F2XWXV2
	active workspace: 3 (3)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.25
	transform: 1
	focused: no
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 3840x2160@60.00Hz 3840x2160@29.98Hz 2560x1440@59.95Hz 2048x1280@59.99Hz 1920x1200@59.88Hz 2048x1080@24.00Hz 1920x1080@60.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1920x1080@24.00Hz 1920x1080@23.98Hz 1600x1200@60.00Hz 1600x900@60.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1152x864@75.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1280x720@50.00Hz 1024x768@75.03Hz 1024x768@60.00Hz 800x600@75.00Hz 800x600@60.32Hz 720x576@50.00Hz 720x576@50.00Hz 720x480@60.00Hz 720x480@60.00Hz 720x480@59.94Hz 720x480@59.94Hz 640x480@75.00Hz 640x480@60.00Hz 640x480@59.94Hz 640x480@59.94Hz 720x400@70.08Hz

Monitor DP-1 (ID 2):
	3440x1440@143.92300 at 1728x786
	description: Acer Technologies XV340CK P T5Y000013E00
	make: Acer Technologies
	model: XV340CK P
	serial: T5Y000013E00
	active workspace: 103 (103)
	special workspace: 0 ()
	reserved: 0 0 0 40
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 3440x1440@143.92Hz 3440x1440@84.96Hz 3440x1440@120.00Hz 3440x1440@59.97Hz 2560x1440@120.00Hz 2560x1440@59.95Hz 1720x1440@59.98Hz 2048x1152@60.00Hz 1920x1200@59.88Hz 1920x1080@120.00Hz 1920x1080@119.88Hz 1920x1080@119.98Hz 1920x1080@60.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1600x1200@60.00Hz 1680x1050@59.95Hz 1600x900@60.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1440x900@143.92Hz1280x800@59.81Hz 1152x864@75.00Hz 1280x720@60.00Hz 1280x720@59.94Hz 1024x768@75.03Hz1024x768@70.07Hz 1024x768@60.00Hz 832x624@74.55Hz 800x600@75.00Hz 800x600@72.19Hz 800x600@60.32Hz 800x600@56.25Hz 720x576@50.00Hz 720x480@60.00Hz 720x480@59.94Hz 640x480@75.00Hz 640x480@72.81Hz 640x480@66.67Hz 640x480@60.00Hz 640x480@59.94Hz 640x480@59.94Hz 720x400@70.08Hz
```

**Comment by PaideiaDilemma** [comment]
@AndreasBack

Please try the -git version of hyprlock. I think this should be fixed with #456.

**Comment by AndreasBackx** [comment]
@PaideiaDilemma thank you, I can confirm it works on 0.5.0. Thank you @vaxerski for the release.

**Comment by AndreasBackx** [comment]
It seems I cheered too soon. The issue still occurs for me, though it was originally fixed.

Can we reopen the issue?

![image](https://github.com/user-attachments/assets/f16e8763-c557-459e-acce-354d18ccfae7)

**Comment by DHDcc** [comment]
yeah, I still have the same issue.

```
❯ hyprlock --version
Hyprlock version 0.5.0
```

```
❯ pacman -Q hyprlock
hyprlock-git 0.5.0.r0.ga093a9ee-1
```

**Comment by PaideiaDilemma** [comment]
Ufff ok @AndreasBackx give me more details.
In the screenshots it seems like hyprlock crashed. does that always happens?
Any particular steps to reproduce? Monitor configuration? I can see that it is rotated but scaled as well?

**Comment by AndreasBackx** [comment]
@PaideiaDilemma I'm perhaps misremembering, though I think I was able to login. I cannot reproduce it now and it's largely fixed. My guess is that I have a bad memory and it likely crashed somehow. I've had quite a few crashes so it wouldn't be too uncommon.

I've not reported them because of a lack of time and it was hard distinguishing the logs from the other logs. It would be nice if the logging had some formatting.

> Any particular steps to reproduce? Monitor configuration? I can see that it is rotated but scaled as well?

My monitor configuration has been posted in a comment above, it's indeed rotated and scaled. Unfortunately I've been unable to reproducing it since your comment, though it happened a few times before.

Is there anything else I can possibly look out for or share that would help?

**Comment by AndreasBackx** [comment]
It was indeed as you said, it was a crash. Here are the logs from everything running on Hyprland, which includes the output of `hyprlock` as it was called with a keybinding.

https://gist.github.com/AndreasBackx/930be2e3acb6349083815250bb7cdd92

What happened was that around 11:45-11:52 I called hyprlock with no arguments. It lead to the same state as the screenshot above. I didn't respond and because I was leaving for lunch and there was a personal chat visible, I changed tty to the one of GDM. (I know people could still switch it back, but it was also not responding so they likely wouldn't be able to get in.) When I came back to my desk just now, about 30 minutes later, I switched the tty back and it seemed like it had crashed entirely because I was prompted for the usual login.

Let me know if there's anything else I can provide or do.

**Comment by PaideiaDilemma** [comment]
@AndreasBackx

A few things regarding your logs:
1. `pidof lock || lock` does not seem to work since `[LOG] onLockFinished called. Seems we got yeeten. Is another lockscreen running?`
2. Can you post `/home/andreasbackx/.cache/hyprland/hyprlandCrashReport3682.txt`? (That is the hyprland crash)
3. Does not contain any information about the hyprlock crash (which needs to happen for the weird screen to show)

Have you used `coredumpctl` before? Maybe you can actually recover some stack traces with that.

But I think I know why your desktop shows trough. That is a Hyprland bug. Will fix that soon.

**Comment by AndreasBackx** [comment]
@PaideiaDilemma

Apologies for the delay, I did not have much time with the machine in question. I think I have got a lead on what might be the issue.

First of all, I think it's a Hyprland issue and not a Hyprlock issue. Not only the desktop showing through, but the crashing part. I'm relatively certain as swaylock experiences it as well and waybar does not show on that monitor either. Though when I replug the monitor, all 3 of those are fixed.

Replugging is a tad annoying for obvious reasons. Though it also moves all workspaces to another display and does not move them back when replugging. I'm unsure if this is expected or not, my guess is that it is not?

I'm not sure what logs or more I can give you to help you debug this however.

> Can you post /home/andreasbackx/.cache/hyprland/hyprlandCrashReport3682.txt? (That is the hyprland crash)


```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Oops

Hyprland received signal 11(SEGV)
Version: 4520b30d498daca8079365bdb909a8dea38e8d55
Tag: v0.44.1
Date: Wed Oct 9 12:54:39 2024
Flags:

System info:
	System name: Linux
	Node name: andreasbackx-fedora-PF4PXZDN
	Release: 6.11.5-200.fc40.x86_64
	Version: #1 SMP PREEMPT_DYNAMIC Tue Oct 22 19:13:11 UTC 2024

GPU:
	64:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev dd) (prog-if 00 [VGA controller])


os-release:
	NAME="Fedora Linux"
	VERSION="40 (Workstation Edition)"
	ID=fedora
	VERSION_ID=40
	VERSION_CODENAME=""
	PLATFORM_ID="platform:f40"
	PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
	ANSI_COLOR="0;38;2;60;110;180"
	LOGO=fedora-logo-icon
	CPE_NAME="cpe:/o:fedoraproject:fedora:40"
	DEFAULT_HOSTNAME="fedora"
	HOME_URL="https://fedoraproject.org/"
	DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
	SUPPORT_URL="https://ask.fedoraproject.org/"
	BUG_REPORT_URL="https://bugzilla.redhat.com/"
	REDHAT_BUGZILLA_PRODUCT="Fedora"
	REDHAT_BUGZILLA_PRODUCT_VERSION=40
	REDHAT_SUPPORT_PRODUCT="Fedora"
	REDHAT_SUPPORT_PRODUCT_VERSION=40
	SUPPORT_END=2025-05-13
	VARIANT="Workstation Edition"
	VARIANT_ID=workstation
Backtrace:
	# | /usr/bin/Hyprland(_Z12getBacktracev+0x60) [0x560b55c50d40]
		getBacktrace()
		??:?
	#1 | /usr/bin/Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0xaa1) [0x560b55be20c1]
		CrashReporter::createAndSaveCrash(int)
		??:?
	#2 | /usr/bin/Hyprland(_Z25handleUnrecoverableSignali+0x68) [0x560b55b7b998]
		handleUnrecoverableSignal(int)
		??:?
	#3 | /lib64/libc.so.6(+0x40d00) [0x7faff024fd00]
		??
		??:0
	#4 | /lib64/libaquamarine.so.3(_ZN10Aquamarine11CDRMBackend14restoreAfterVTEv+0x51c) [0x7faff0fa897c]
		??
		??:0
	#5 | /lib64/libaquamarine.so.3(+0xadeb8) [0x7faff0fbdeb8]
		??
		??:0
	#6 | /lib64/libhyprutils.so.1(_ZN9Hyprutils6Signal15CSignalListener4emitESt3any+0x5f) [0x7faff0d0c0ef]
		??
		??:0
	#7 | /lib64/libhyprutils.so.1(_ZN9Hyprutils6Signal7CSignal4emitESt3any+0x1ed) [0x7faff0d0c44d]
		??
		??:0
	#8 | /lib64/libaquamarine.so.3(+0x746c3) [0x7faff0f846c3]
		??
		??:0
	#9 | /lib64/libseat.so.1(+0x379a) [0x7faff06ae79a]
		??
		??:0
	#1 | /lib64/libsystemd.so.0(+0x26884) [0x7fafef57f884]
		??
		??:0
	#11 | /lib64/libsystemd.so.0(+0x267ce) [0x7fafef57f7ce]
		??
		??:0
	#12 | /lib64/libsystemd.so.0(+0x26620) [0x7fafef57f620]
		??
		??:0
	#13 | /lib64/libsystemd.so.0(+0x267ce) [0x7fafef57f7ce]
		??
		??:0
	#14 | /lib64/libsystemd.so.0(+0x26620) [0x7fafef57f620]
		??
		??:0
	#15 | /lib64/libsystemd.so.0(+0x267ce) [0x7fafef57f7ce]
		??
		??:0
	#16 | /lib64/libsystemd.so.0(+0x26620) [0x7fafef57f620]
		??
		??:0
	#17 | /lib64/libsystemd.so.0(+0x267ce) [0x7fafef57f7ce]
		??
		??:0
	#18 | /lib64/libsystemd.so.0(+0x26620) [0x7fafef57f620]
		??
		??:0
	#19 | /lib64/libsystemd.so.0(+0x267ce) [0x7fafef57f7ce]
		??
		??:0
	#2 | /lib64/libsystemd.so.0(+0x2678e) [0x7fafef57f78e]
		??
		??:0
	#21 | /lib64/libsystemd.so.0(+0x2695f) [0x7fafef57f95f]
		??
		??:0
	#22 | /lib64/libsystemd.so.0(+0x4bae3) [0x7fafef5a4ae3]
		??
		??:0
	#23 | /lib64/libseat.so.1(+0x3df6) [0x7faff06aedf6]
		??
		??:0
	#24 | /lib64/libaquamarine.so.3(_ZN10Aquamarine8CSession21dispatchLibseatEventsEv+0x2c) [0x7faff0f8cf6c]
		??
		??:0
	#25 | /usr/bin/Hyprland(+0x30127a) [0x560b55cd027a]
		CXCursorManager::getShape(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, float)
		??:?
	#26 | /lib64/libwayland-server.so.0(wl_event_loop_dispatch+0x1f2) [0x7faff0ee7c92]
		??
		??:0
	#27 | /lib64/libwayland-server.so.0(wl_display_run+0x35) [0x7faff0ee9cf5]
		??
		??:0
	#28 | /usr/bin/Hyprland(_ZN17CEventLoopManager9enterLoopEv+0x2a5) [0x560b55cd36d5]
		CEventLoopManager::enterLoop()
		??:?
	#29 | /usr/bin/Hyprland(main+0x9a7) [0x560b55b0d247]
		main
		??:?
	#3 | /lib64/libc.so.6(+0x2a088) [0x7faff0239088]
		??
		??:0
	#31 | /lib64/libc.so.6(__libc_start_main+0x8b) [0x7faff023914b]
		??
		??:0
	#32 | /usr/bin/Hyprland(_start+0x25) [0x560b55b3d705]
		_start
		??:?


Log tail:
[ERR] [AQ] drm: No format for output
[ERR] output DP-1 failed basic test on format DRM_FORMAT_INVALID
[LOG] CMonitorState::ensureBufferPresent: no buffer or mismatched format, attaching one from the swapchain for modeset being possible
[ERR] [AQ] drm: No format for output
[ERR] Couldn't commit output named DP-1
[LOG] Monitor DP-1 -> destroyed all render data
[LOG] arrangeMonitors: 3 to arrange
[LOG] arrangeMonitors: HDMI-A-1 explicit [5168, 226]
[LOG] arrangeMonitors: DP-8 explicit [0, 0]
[LOG] arrangeMonitors: DP-1 explicit [1728, 786]
[LOG] arrangeMonitors: HDMI-A-1 xwayland [0, 0]
[LOG] arrangeMonitors: DP-8 xwayland [1440, 0]
[LOG] arrangeMonitors: DP-1 xwayland [3600, 0]
[LOG] [CXDGOutputProtocol] updating all xdg_output heads
[LOG] Monitor DP-1 data dump: res 3440x1440@143.92Hz, scale 1.00, transform 0, pos 1728x786, 10b 0
[LOG] [CXDGOutputProtocol] updating all xdg_output heads
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 177
[LOG] CMonitorState::ensureBufferPresent: no buffer or mismatched format, attaching one from the swapchain for modeset being possible
[ERR] [AQ] drm: No format for output
[WARN] state.commit() failed in CMonitor::onCommit
[LOG] Added new monitor with name DP-1 at [1728, 786] with size [3440, 1440], pointer 560b852ca230
[LOG] New monitor: WORKSPACEID 101, exists: 1
[LOG] moveWorkspaceToMonitor: Moving 101 to monitor 2
[ERR] [../src/protocols/core/Compositor.cpp:196] enter() called on a defunct output global
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 177
[LOG] [IWaylandProtocol] Registered global [WLOutput (DP-1)]
[LOG] [CLinuxDMABufV1Protocol] Resetting format table
[LOG] arrangeMonitors: 3 to arrange
[LOG] arrangeMonitors: HDMI-A-1 explicit [5168, 226]
[LOG] arrangeMonitors: DP-8 explicit [0, 0]
[LOG] arrangeMonitors: DP-1 explicit [1728, 786]
[LOG] arrangeMonitors: HDMI-A-1 xwayland [0, 0]
[LOG] arrangeMonitors: DP-8 xwayland [1440, 0]
[LOG] arrangeMonitors: DP-1 xwayland [3600, 0]
[LOG] [CXDGOutputProtocol] updating all xdg_output heads
[ERR] [../src/protocols/core/Compositor.cpp:203] Cannot enter surface 560b8647d890 to DP-1, client hasn't bound the output
[WARN] Attempted to render frame on inactive session!
[LOG] [AQ] drm: Scanning connector id 115
[LOG] [AQ] drm: Connector id 115 already initialized
[LOG] [AQ] drm: Connector 115 connection state: 2
[LOG] [AQ] drm: Scanning connector id 120
[LOG] [AQ] drm: Connector id 120 already initialized
[LOG] [AQ] drm: Connector 120 connection state: 2
[LOG] [AQ] drm: Scanning connector id 125
[LOG] [AQ] drm: Connector id 125 already initialized
[LOG] [AQ] drm: Connector 125 connection state: 2
[LOG] [AQ] drm: Scanning connector id 130
[LOG] [AQ] drm: Connector id 130 already initialized
[LOG] [AQ] drm: Connector 130 connection state: 2
[LOG] [AQ] drm: Scanning connector id 135
[LOG] [AQ] drm: Connector id 135 already initialized
[LOG] [AQ] drm: Connector 135 connection state: 2
[LOG] [AQ] drm: Scanning connector id 156
[LOG] [AQ] drm: Connector id 156 already initialized
[LOG] [AQ] drm: Connector 156 connection state: 2
[LOG] [AQ] drm: Scanning connector id 159
[LOG] [AQ] drm: Connector id 159 already initialized
[LOG] [AQ] drm: connector DP-8 crtc is incapable of vrr: props.vrr_capable -> 0, crtc->props.vrr_enabled -> 24
[LOG] [AQ] drm: Explicit sync supported
[LOG] [AQ] drm: connector DP-8 crtc supports CTM
[LOG] [AQ] drm: Connector 159 connection state: 1
[LOG] [AQ] drm: Scanning connector id 162
[LOG] [AQ] drm: Connector id 162 already initialized
[LOG] [AQ] drm: Connector 162 connection state: 2
[LOG] [AQ] drm: Rescanned connectors
[ERR] [AQ] atomic drm request: failed to commit: No such file or directory, flags: ATOMIC_ALLOW_MODESET 
[ERR] [AQ] drm: failed reset
[LOG] [AQ] drm: Restoring crtc 79 with clock 500840 hdisplay 2880 vdisplay 1800 vrefresh 90
[ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags: ATOMIC_ALLOW_MODESET 
[ERR] [AQ] drm: crtc 79 failed restore
[LOG] [AQ] drm: Restoring crtc 83 with clock 241500 hdisplay 2560 vdisplay 1440 vrefresh 60
```

> Have you used coredumpctl before? Maybe you can actually recover some stack traces with that.

Unfortunately not.

If there is anything else that you need and I can provide. Let me know.
