### ISSUE TITLE
Halign aligns with an offset to the right

### ISSUE THREAD

**Issue by NOTMASTER09** [hyprwm/hyprlock#516]
### Regression?

No

### Hyprlock Info and Version

0.4.1
<details> <summary>Hyprlock config</summary>

```sh
general {
  hide_cursor = true
}

#background {
#  path = screenshot
#  blur_passes = 2
#}

label {
  text = HELLO
  text_align = center
  halign = center
  valign = center
  position = 0,0
}
```
</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.2


flags: (if any)


System Information:
System name: Linux
Node name: aphrodite
Release: 6.11.3-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 20:11:06 +0000


GPU information: 
c1:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c4) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

A label widget with `halign: center` is not, in fact, aligned to the center, using `halign:left` renders completely off-screen

### How to reproduce

I don't know if this is because of my 3:2 display ratio or something else entirely

### Crash reports, logs, images, videos

Screenshot of the issue:
![screen](https://github.com/user-attachments/assets/086ce187-bdfb-4017-9f7d-fba855cb4c92)
Logs in text form:
```sh
[ERR] Config has errors:
Config error in file /home/user/.config/hypr/hyprlock.conf at line 16: failed parsing a vec2: no space
Proceeding ignoring faulty entries
[LOG]   | got iface: wl_seat v9
[LOG]    > Bound to wl_seat v9
[LOG]   | got iface: wl_data_device_manager v3
[LOG]   | got iface: wl_compositor v6
[LOG]    > Bound to wl_compositor v6
[LOG]   | got iface: wl_subcompositor v1
[LOG]   | got iface: wl_shm v1
[LOG]   | got iface: wp_viewporter v1
[LOG]    > Bound to wp_viewporter v1
[LOG]   | got iface: wp_tearing_control_manager_v1 v1
[LOG]   | got iface: wp_fractional_scale_manager_v1 v1
[LOG]    > Bound to wp_fractional_scale_manager_v1 v1
[LOG]   | got iface: zxdg_output_manager_v1 v3
[LOG]   | got iface: wp_cursor_shape_manager_v1 v1
[LOG]    > Bound to wp_cursor_shape_manager_v1 v1
[LOG]   | got iface: zwp_idle_inhibit_manager_v1 v1
[LOG]   | got iface: zwp_relative_pointer_manager_v1 v1
[LOG]   | got iface: zxdg_decoration_manager_v1 v1
[LOG]   | got iface: wp_alpha_modifier_v1 v1
[LOG]   | got iface: zwlr_gamma_control_manager_v1 v1
[LOG]   | got iface: ext_foreign_toplevel_list_v1 v1
[LOG]   | got iface: zwp_pointer_gestures_v1 v3
[LOG]   | got iface: zwlr_foreign_toplevel_manager_v1 v3
[LOG]   | got iface: zwp_keyboard_shortcuts_inhibit_manager_v1 v1
[LOG]   | got iface: zwp_text_input_manager_v1 v1
[LOG]   | got iface: zwp_text_input_manager_v3 v1
[LOG]   | got iface: zwp_pointer_constraints_v1 v1
[LOG]   | got iface: zwlr_output_power_manager_v1 v1
[LOG]   | got iface: xdg_activation_v1 v1
[LOG]   | got iface: ext_idle_notifier_v1 v1
[LOG]   | got iface: ext_session_lock_manager_v1 v1
[LOG]    > Bound to ext_session_lock_manager_v1 v1
[LOG]   | got iface: zwp_input_method_manager_v2 v1
[LOG]   | got iface: zwp_virtual_keyboard_manager_v1 v1
[LOG]   | got iface: zwlr_virtual_pointer_manager_v1 v2
[LOG]   | got iface: zwlr_output_manager_v1 v4
[LOG]   | got iface: org_kde_kwin_server_decoration_manager v1
[LOG]   | got iface: hyprland_focus_grab_manager_v1 v1
[LOG]   | got iface: zwp_tablet_manager_v2 v1
[LOG]   | got iface: zwlr_layer_shell_v1 v5
[LOG]   | got iface: wp_presentation v1
[LOG]   | got iface: xdg_wm_base v6
[LOG]   | got iface: zwlr_data_control_manager_v1 v2
[LOG]   | got iface: zwp_primary_selection_device_manager_v1 v1
[LOG]   | got iface: xwayland_shell_v1 v1
[LOG]   | got iface: zwlr_screencopy_manager_v1 v3
[LOG]    > Bound to zwlr_screencopy_manager_v1 v3
[LOG]   | got iface: hyprland_toplevel_export_manager_v1 v2
[LOG]   | got iface: hyprland_global_shortcuts_manager_v1 v1
[LOG]   | got iface: xdg_dialog_v1 v1
[LOG]   | got iface: wp_single_pixel_buffer_manager_v1 v1
[LOG]   | got iface: wp_drm_lease_device_v1 v1
[LOG]   | got iface: wp_linux_drm_syncobj_manager_v1 v1
[LOG]   | got iface: wl_drm v2
[LOG]   | got iface: zwp_linux_dmabuf_v1 v5
[LOG]    > Bound to zwp_linux_dmabuf_v1 v5
[LOG]   | got iface: wl_output v4
[LOG]    > Bound to wl_output v4
[LOG] [core] dmabufFeedbackMainDevice
[LOG] output 49 name eDP-1
[LOG] output 49 description BOE 0x0BCA  (eDP-1)
[LOG] output 49 make BOE model 0x0BCA
[LOG] output 49 done
[LOG] Running on Hyprland
[LOG] Locking session
[LOG] Got fractional scale: 1
[LOG] Got fractional scale: 1.5666667
[LOG] configure with serial 46026
[LOG] Configuring surface for logical [Vector2D: x: 1440, y: 960] and pixel [Vector2D: x: 2256, y: 1504]
[LOG] Got fractional scale: 1.5666667
[LOG] configure with serial 46026
[LOG] Configuring surface for logical [Vector2D: x: 1440, y: 960] and pixel [Vector2D: x: 2256, y: 1504]
[LOG] onLockLocked called
[LOG] Authenticating
[LOG] PAM_PROMPT: Enter Password or Place finger on fingerprint reader: 

[LOG] auth: authenticated for hyprlock
[LOG] Unlocking session
[LOG] Unlocked, exiting!
[LOG] Reached the end, exiting
```

**Comment by PaideiaDilemma** [comment]
Should be fixed in 0.5.0 if I remember correctly.
Can you test it?

**Comment by NOTMASTER09** [comment]
Tested on 0.5.0, the issue still persists
Config file:
```
general {
  hide_cursor = true
  enable_fingerprint = true
}

background {
  path = screenshot
  blur_passes = 2
}

label {
  valign = center
  halign = center
  text = HELLO
}
```
Output log with `-v`:
[log.txt](https://github.com/user-attachments/files/17507211/log.txt)
Screenshot:
![screen](https://github.com/user-attachments/assets/b7e53299-b54a-46d6-8c8b-75a264b5ce00)

**Comment by PaideiaDilemma** [comment]
You should probably use `position` explicitly. But I made a MR that would fix this behavior.
