### ISSUE TITLE
Desktop briefly flashes and gets focused before hyprlock is opened upon the system moving out of suspend

### ISSUE THREAD

**Issue by FarrenHawk** [hyprwm/hyprlock#633]
When I open my laptop lid, I briefly see my desktop, and then hyprlock shows up. This is with a bone stock hypridle config (the code from the example hypridle config on the hyprland wiki), even worse, hyprlock isn't focused, so unless I move my mouse, I type in other applications.

I shouldn't have to state why this is an absolutely horrible security hole, but more importantly for me, it's just plain annoying.

here's my hypridle config:
```
general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 150                                # 2.5min.
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}

listener {
    timeout = 300                                 # 5min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 330                                 # 5.5min
    on-timeout = hyprctl dispatch dpms off        # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 1200                                # 20min
    on-timeout = systemctl suspend                # suspend pc
}
```

I've tried futzing around with the `before_sleep_cmd` in my hypridle config by changing it to activate `hyprlock --immediate` to no avail, as well as adding lines to my `hyprland.conf` that either run `systemctl suspend` or `hyprlock --immediate` on laptop lid close (and the latter of which I also tried on laptop lid open. But when I ran hyprlock on both lid close and lid open, hyprlock was frozen entirely)

Any help/advice? I really love hyprlock because of how damn good looking it is, I really want it to work.

**Comment by winkelnp** [comment]
I also had this issue and use a workaroud with a systemd service that runs before `sleep.target`
I'm not sure where this problem is caused, but this seems to fix it (for now):

```desktop
/etc/systemd/system/user-suspend@.service
-----
[Unit]
Description=User Suspend Actions
Before=sleep.target

[Service]
User=%i
Type=simple
Environment=XDG_RUNTIME_DIR="/run/user/$(id -u %i)"
ExecStart=/usr/bin/hyprlock # This fails and then hypridle triggers hyprlock - no clue why this works
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=sleep.target
```

activate with `systemctl enable user-suspend@{your username}.service`

**Comment by FarrenHawk** [comment]
Oh, that's awesome!! Glad I'm not the only one with this issue, seems to be a not insignificant issue. I'll try that!!

**Comment by brielov** [comment]
I'm having the same issue. Whenever I open my laptop's lid, I type my password but the input is not focused. So I type it again and when it unlocks, i can see my password written in firefox or whatever program was focused behind hyprlock.

**Comment by willisplummer** [comment]
I'm using the updated hypridle (hyprlock-lock-notify-v1) and still getting this issue

**Comment by PaideiaDilemma** [comment]
@willisplummer please share you config and hypridle logs if you can.

there are also some logind settings that make it so clients can't inhibit sleep. so maybe it's that.

**Comment by willisplummer** [comment]
here's my [home-manager config for hypridle](https://github.com/willisplummer/nixos/blob/main/hosts/default/home.nix#L451-L487)

and here's the output:
```
general {
  after_sleep_cmd=hyprctl dispatch dpms on
  before_sleep_cmd=loginctl lock-session
  ignore_dbus_inhibit=false
  ignore_systemd_inhibit=false
  inhibit_sleep=3
  lock_cmd=pidof hyprlock || hyprlock
}

listener {
  on-resume=brightnessctl -r
  on-timeout=brightnessctl -s set 30
  timeout=240
}

listener {
  on-timeout=loginctl lock-session
  timeout=300
}

listener {
  on-resume=hyprctl dispatch dpms on
  on-timeout=hyprctl dispatch dpms off
  timeout=360
}

listener {
  on-timeout=systemctl suspend
  timeout=420
}
```

**Comment by PaideiaDilemma** [comment]
@willisplummer 
https://github.com/willisplummer/nixos/commit/ad3ba0486de90198132b40328e3165cf1e580227#commitcomment-152041597

you are not using latest hypridle. `journalctl` is your friend. Check `journalctl --user -u hypridle`

**Comment by willisplummer** [comment]
thanks for pointing out that i wasn't doing the flake override correctly. i've addressed that in my config and after a reboot it seems like it's working.

**Comment by PaideiaDilemma** [comment]
I am going to close this. Fixed by https://github.com/hyprwm/hypridle/pull/122 : )

**Comment by tstsrt** [comment]
Sorry, but the issue still persists for me. Here's my hypridle config:
```
general {
    lock_cmd = pidof hyprlock || /home/username/Cpp/hyprlock/build/hyprlock
    before_sleep_cmd = loginctl lock-session
    inhibit_sleep = 3
}
```
and the hypridle log:
<details>
<summary>hypridle log</summary>

```
[ERR] Config has errors:
No rules configured
Proceeding ignoring faulty entries
[LOG]   | got iface: wl_seat v9
[LOG]    > Bound to wl_seat v9
[LOG]   | got iface: wl_data_device_manager v3
[LOG]   | got iface: wl_compositor v6
[LOG]   | got iface: wl_subcompositor v1
[LOG]   | got iface: wl_shm v1
[LOG]   | got iface: wp_viewporter v1
[LOG]   | got iface: wp_tearing_control_manager_v1 v1
[LOG]   | got iface: wp_fractional_scale_manager_v1 v1
[LOG]   | got iface: zxdg_output_manager_v1 v3
[LOG]   | got iface: wp_cursor_shape_manager_v1 v1
[LOG]   | got iface: zwp_idle_inhibit_manager_v1 v1
[LOG]   | got iface: zwp_relative_pointer_manager_v1 v1
[LOG]   | got iface: zxdg_decoration_manager_v1 v1
[LOG]   | got iface: wp_alpha_modifier_v1 v1
[LOG]   | got iface: zwlr_gamma_control_manager_v1 v1
[LOG]   | got iface: ext_foreign_toplevel_list_v1 v1
[LOG]   | got iface: zwp_pointer_gestures_v1 v3
[LOG]   | got iface: zwlr_foreign_toplevel_manager_v1 v3
[LOG]   | got iface: zwp_keyboard_shortcuts_inhibit_manager_v1 v1
[LOG]   | got iface: zwp_text_input_manager_v1 v1
[LOG]   | got iface: zwp_text_input_manager_v3 v1
[LOG]   | got iface: zwp_pointer_constraints_v1 v1
[LOG]   | got iface: zwlr_output_power_manager_v1 v1
[LOG]   | got iface: xdg_activation_v1 v1
[LOG]   | got iface: ext_idle_notifier_v1 v2
[LOG]    > Bound to ext_idle_notifier_v1 v2
[LOG]   | got iface: hyprland_lock_notifier_v1 v1
[LOG]    > Bound to hyprland_lock_notifier_v1 v1
[LOG]   | got iface: ext_session_lock_manager_v1 v1
[LOG]   | got iface: zwp_input_method_manager_v2 v1
[LOG]   | got iface: zwp_virtual_keyboard_manager_v1 v1
[LOG]   | got iface: zwlr_virtual_pointer_manager_v1 v2
[LOG]   | got iface: zwlr_output_manager_v1 v4
[LOG]   | got iface: org_kde_kwin_server_decoration_manager v1
[LOG]   | got iface: hyprland_focus_grab_manager_v1 v1
[LOG]   | got iface: zwp_tablet_manager_v2 v1
[LOG]   | got iface: zwlr_layer_shell_v1 v5
[LOG]   | got iface: wp_presentation v1
[LOG]   | got iface: xdg_wm_base v6
[LOG]   | got iface: zwlr_data_control_manager_v1 v2
[LOG]   | got iface: zwp_primary_selection_device_manager_v1 v1
[LOG]   | got iface: xwayland_shell_v1 v1
[LOG]   | got iface: zwlr_screencopy_manager_v1 v3
[LOG]   | got iface: hyprland_toplevel_export_manager_v1 v2
[LOG]   | got iface: hyprland_global_shortcuts_manager_v1 v1
[LOG]   | got iface: xdg_wm_dialog_v1 v1
[LOG]   | got iface: wp_single_pixel_buffer_manager_v1 v1
[LOG]   | got iface: wp_security_context_manager_v1 v1
[LOG]   | got iface: hyprland_ctm_control_manager_v1 v2
[LOG]   | got iface: hyprland_surface_manager_v1 v2
[LOG]   | got iface: wp_content_type_manager_v1 v1
[LOG]   | got iface: wp_color_manager_v1 v1
[LOG]   | got iface: wp_drm_lease_device_v1 v1
[LOG]   | got iface: wp_linux_drm_syncobj_manager_v1 v1
[LOG]   | got iface: wl_drm v2
[LOG]   | got iface: zwp_linux_dmabuf_v1 v5
[LOG]   | got iface: wl_output v4
[LOG] found 0 rules
[LOG] wayland done, registering dbus
[LOG] Sleep inhibition enabled - inhibiting until the wayland session gets locked
[LOG] Using dbus path /org/freedesktop/login1/session/_31
[LOG] Inhibited sleep with fd 10
[LOG] Got PrepareForSleep from dbus with sleep true
[LOG] Executing loginctl lock-session
[LOG] Process Created with pid 79064
[LOG] Got dbus .Session
[LOG] Got Lock from dbus
[LOG] Locking with pidof hyprlock || /home/username/Cpp/hyprlock/build/hyprlock
[LOG] Executing pidof hyprlock || /home/username/Cpp/hyprlock/build/hyprlock
[LOG] Process Created with pid 79074
Hyprlock version v0.7.0 (commit 6daab05)
[LOG]   | got iface: wl_seat v9
[LOG]    > Bound to wl_seat v9
[LOG]   | got iface: wl_data_device_manager v3
[LOG]   | got iface: wl_compositor v6
[LOG]    > Bound to wl_compositor v6
[LOG]   | got iface: wl_subcompositor v1
[LOG]   | got iface: wl_shm v1
[LOG]    > Bound to wl_shm v1
[LOG]   | got iface: wp_viewporter v1
[LOG]    > Bound to wp_viewporter v1
[LOG]   | got iface: wp_tearing_control_manager_v1 v1
[LOG]   | got iface: wp_fractional_scale_manager_v1 v1
[LOG]    > Bound to wp_fractional_scale_manager_v1 v1
[LOG]   | got iface: zxdg_output_manager_v1 v3
[LOG]   | got iface: wp_cursor_shape_manager_v1 v1
[LOG]    > Bound to wp_cursor_shape_manager_v1 v1
[LOG]   | got iface: zwp_idle_inhibit_manager_v1 v1
[LOG]   | got iface: zwp_relative_pointer_manager_v1 v1
[LOG]   | got iface: zxdg_decoration_manager_v1 v1
[LOG]   | got iface: wp_alpha_modifier_v1 v1
[LOG]   | got iface: zwlr_gamma_control_manager_v1 v1
[LOG]   | got iface: ext_foreign_toplevel_list_v1 v1
[LOG]   | got iface: zwp_pointer_gestures_v1 v3
[LOG]   | got iface: zwlr_foreign_toplevel_manager_v1 v3
[LOG]   | got iface: zwp_keyboard_shortcuts_inhibit_manager_v1 v1
[LOG]   | got iface: zwp_text_input_manager_v1 v1
[LOG]   | got iface: zwp_text_input_manager_v3 v1
[LOG]   | got iface: zwp_pointer_constraints_v1 v1
[LOG]   | got iface: zwlr_output_power_manager_v1 v1
[LOG]   | got iface: xdg_activation_v1 v1
[LOG]   | got iface: ext_idle_notifier_v1 v2
[LOG]   | got iface: hyprland_lock_notifier_v1 v1
[LOG]   | got iface: ext_session_lock_manager_v1 v1
[LOG]    > Bound to ext_session_lock_manager_v1 v1
[LOG]   | got iface: zwp_input_method_manager_v2 v1
[LOG]   | got iface: zwp_virtual_keyboard_manager_v1 v1
[LOG]   | got iface: zwlr_virtual_pointer_manager_v1 v2
[LOG]   | got iface: zwlr_output_manager_v1 v4
[LOG]   | got iface: org_kde_kwin_server_decoration_manager v1
[LOG]   | got iface: hyprland_focus_grab_manager_v1 v1
[LOG]   | got iface: zwp_tablet_manager_v2 v1
[LOG]   | got iface: zwlr_layer_shell_v1 v5
[LOG]   | got iface: wp_presentation v1
[LOG]   | got iface: xdg_wm_base v6
[LOG]   | got iface: zwlr_data_control_manager_v1 v2
[LOG]   | got iface: zwp_primary_selection_device_manager_v1 v1
[LOG]   | got iface: xwayland_shell_v1 v1
[LOG]   | got iface: zwlr_screencopy_manager_v1 v3
[LOG]    > Bound to zwlr_screencopy_manager_v1 v3
[LOG]   | got iface: hyprland_toplevel_export_manager_v1 v2
[LOG]   | got iface: hyprland_global_shortcuts_manager_v1 v1
[LOG]   | got iface: xdg_wm_dialog_v1 v1
[LOG]   | got iface: wp_single_pixel_buffer_manager_v1 v1
[LOG]   | got iface: wp_security_context_manager_v1 v1
[LOG]   | got iface: hyprland_ctm_control_manager_v1 v2
[LOG]   | got iface: hyprland_surface_manager_v1 v2
[LOG]   | got iface: wp_content_type_manager_v1 v1
[LOG]   | got iface: wp_color_manager_v1 v1
[LOG]   | got iface: wp_drm_lease_device_v1 v1
[LOG]   | got iface: wp_linux_drm_syncobj_manager_v1 v1
[LOG]   | got iface: wl_drm v2
[LOG]   | got iface: zwp_linux_dmabuf_v1 v5
[LOG]    > Bound to zwp_linux_dmabuf_v1 v5
[LOG]   | got iface: wl_output v4
[LOG]    > Bound to wl_output v4
[LOG] Exposed seat name: Hyprland
[LOG] [core] dmabufFeedbackMainDevice
[LOG] output eDP-1 name eDP-1
[LOG] output 55 description BOE 0x07A3  (eDP-1)
[LOG] output 55 make BOE model 0x07A3
[LOG] output 55 done
[LOG] Running on Hyprland
[LOG] Locking session
[LOG] Starting fade in
[LOG] Got fractional scale: 100.0%
[LOG] configure with serial 346520
[LOG] Configuring surface for logical [Vector2D: x: 1920, y: 1080] and pixel [Vector2D: x: 1920, y: 1080]
[LOG] Wayland session got locked
[LOG] Executing
[LOG] onLockLocked called
[LOG] Process Created with pid 79093
[LOG] Releasing the sleep inhibitor!
[LOG] Got PrepareForSleep from dbus with sleep false
[LOG] output 55 make BOE model 0x07A3
[LOG] output 55 done
[LOG] configure with serial 346526
[LOG] Configuring surface for logical [Vector2D: x: 1920, y: 1080] and pixel [Vector2D: x: 1920, y: 1080]
[LOG] output 55 done
[LOG] output 55 make BOE model 0x07A3
[LOG] output 55 done
[LOG] configure with serial 346527
[LOG] Configuring surface for logical [Vector2D: x: 1920, y: 1080] and pixel [Vector2D: x: 1920, y: 1080]
[LOG] output 55 done
[LOG] Authenticating
[LOG] PAM_PROMPT: Password:
[LOG] auth: authenticated for hyprlock
[LOG] Unlocking session
[LOG] Unlocked, exiting!
[LOG] Wayland session got unlocked
[LOG] Inhibited sleep with fd 10
[LOG] Executing
[LOG] Process Created with pid 79183
[LOG] Reached the end, exiting
```

</details>

**Comment by nanuwo** [comment]
If people have animations enabled, this shouldn't cause such a security hole. Maybe disable them before suspend?

**Comment by PaideiaDilemma** [comment]
I agree. The problem is that hyprlock does not know when we are suspending.
There is the `--immediate` flag, which people using the `grace` setting need to assure it locks right away.

So I propose to disable fade-in when `--immediate` is specified.
Then that should be used for `before_sleep` commands.

**Comment by PaideiaDilemma** [comment]
Hmm, show me your hydride logs please. Also try `--immediate-render`.

**Comment by PaideiaDilemma** [comment]
Hmm I guess let's use this new issue that was opened: #780
