### ISSUE TITLE
dynamic text fields in labels are not working

### ISSUE THREAD

**Issue by msmafra** [hyprwm/hyprlock#770]
### Regression?

Yes, No

### Hyprlock Info and Version

❯ hyprlock --version
Hyprlock version v0.8.2
<details> <summary>Hyprlock config</summary>

```sh
source = ~/.config/hypr/conf/preferences.conf
source = ~/.config/hypr/conf/colors.conf

general {
    text_trim = false
    hide_cursor = false
    grace = 0
    immediate_render = true
    fractional_scaling = 2
    screencopy_mode = 1
    fail_timeout = 200
}

auth {
    pam {
        enabled = true
        module = hyprlock
    }
}

animations {
    enabled = true
    bezier = easeInOutSine, 0.37, 0, 0.63, 1
    animation = fadeIn, 1, 5, easeInOutSine, fade
    animation = fadeOut, 1, 5, easeInOutSine, fade
    animation = inputFieldColors, 1, 2, easeInOutSine, fade
    animation = inputFieldFade, 1, 2, easeInOutSine, fade_on_empty
    animation = inputFieldWidth, 1, 2, easeInOutSine, fade
    animation = inputFieldDots, 1, 2, easeInOutSine, fade
}

input-field {
    monitor =
    size = 350, 45
    outline_thickness = 2
    position = 0, -120
    halign = center
    valign = center
    rounding = 2
    dots_size = 0.3
    dots_spacing = 0.7
    dots_center = false
    dots_text_format = 󰨓
    outer_color = $lighttext
    inner_color = $mainbackground
    font_color = $alternatetext
    check_color = $maincritical
    fade_on_empty = true
    placeholder_text = <b>...</b>
    fail_color = $secondarycritical
    fail_text = <span>$FAIL <b>($ATTEMPTS)</b></span>
}

background {
     monitor =
     color = $mainbackground
     path = $conf_dir/hyprlock-background
     #blur_passes = 2
     #blur_size = 3
     #noise = 0.0117
     #contrast = 0.8916
     #brightness = 0.1
     #vibrancy = 0.9
     #vibrancy_darkness = 0.9
 }

image {
    path = /var/lib/AccountsService/icons/$USER
    size = 128
    position = 0, 30
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $blue-shadow
}

label {
    font_family = Inter Variable Bold
    font_size = 32
    color = $lighttext
    text = $USER
    text_align = center
    position = 0, -65
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 3
    shadow_color = $blue-shadow
}
label {
    font_family = Inter Variable Bold
    font_size = 32
    color = $lighttext
    text = $USER
    text_align = center
    position = 0, -63
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 3
    shadow_color = $blue-shadow
}

# test using label from documentation
label {
    monitor =
    text = cmd[update:1000] echo "<span foreground='##ff2222'>$(date)</span>"
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = Noto Sans

    position = 0, 80
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%-H:%M%p")"
    color = $pessego
    font_size = 120
    font_family = Inter Variable Bold
    position = 0, -25
    halign = center
    valign = top
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $blue-shadow
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%-H:%M%p")"
    color = $pessego
    font_size = 120
    font_family = Inter Variable Bold
    position = 0, -22
    halign = center
    valign = top
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $blue-shadow
}

# DAY-DATE-MONTH
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date '+%A, %d %B de %Y')</span>"
    color = $laranja
    font_size = 16
    font_family = Inter Variable Bold
    position = 0, -180
    halign = center
    valign = top
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $blue-shadow
}
# DAY-DATE-MONTH
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date '+%A, %d %B de %Y')</span>"
    color = $laranja
    font_size = 16
    font_family = Inter Variable Bold
    position = 0, -178
    halign = center
    valign = top
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $blue-shadow
}
#$maincritical = rgb(207, 34, 50)
#$secondarycritical = rgb(238, 67, 76)
#$rose = rgb(255, 220, 222)
#$darkrose = rgb(233, 119, 119)
#$darkpink = rgb(185, 139, 149)
#$darkerpink = rgb(171, 106, 151)
#$darkred = rgb(119, 8, 15)
#$mainred = rgb(193, 18, 31)
#$darkerred = rgb(107, 34, 50)

label {
    monitor =
    text = $LAYOUT
    color = $deep-blue
    font_size = 10
    font_family = Inter Variable Bold
    position = 0, -520
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $brightext
}
label {
    monitor =
    text = $LAYOUT
    color = $deep-blue
    font_size = 10
    font_family = Inter Variable Bold
    position = 0, -518
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
    shadow_color = $brightext
}

```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.48.1 built from branch  at commit 29e2e59fdbab8ed2cc23a20e3c6043d5decb5cdc  (version: bump to v0.48.1).
Date: Fri Mar 28 16:16:07 2025
Tag: v0.48.1, commits: 5937
built against:
 aquamarine 0.8.0
 hyprlang 0.6.1
 hyprutils 0.7.0
 hyprcursor 0.1.12
 hyprgraphics 0.1.3


no flags were set


System Information:
System name: Linux
Node name: tars
Release: 6.14.5-300.fc42.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Fri May  2 14:16:46 UTC 2025


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106M [GeForce RTX 2060 Mobile] [10de:1f15] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  570.144  Thu Apr 10 20:33:29 UTC 2025


os-release: NAME="Fedora Linux"
VERSION="42 (Workstation Edition)"
RELEASE_TYPE=stable
ID=fedora
VERSION_ID=42
VERSION_CODENAME=""
PLATFORM_ID="platform:f42"
PRETTY_NAME="Fedora Linux 42 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:42"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f42/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=42
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=42
SUPPORT_END=2026-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation


plugins:
  xtra-dispatchers by Vaxry ver 1.0

======Config-Start======


Config File: /home/coop/.config/hypr/hyprland.conf: Read Succeeded
# BASED ON CACHYOS'S CONFIG
# MY CONFIGURATIONS SINCE 0.45.0
# Note: if theming, change colors.conf and preferences.conf or create
# a different colors.conf and preferences.conf
# Environment variables
# disabled in favor of UWSM files env and env-hyprland inside
# $HOME/.config/uwsm
#source = ~/.config/hypr/conf/envs.conf

# My preferences/variables/settings
source = ~/.config/hypr/conf/preferences.conf

# XDG user dirs
#source = ~/.config/hypr/conf/xdg-dirs-localized.conf

# My theme
source = ~/.config/hypr/conf/colors.conf

# Default autostart
source = ~/.config/hypr/conf/autostart.conf

# Display configuration
source = ~/.config/hypr/conf/monitors.conf

# Default keybinds
source = ~/.config/hypr/conf/keybinds.conf

# Window rules
source = ~/.config/hypr/conf/windows.conf

# Workspace rules
source = ~/.config/hypr/conf/workspaces.conf

# Layer rules
source = ~/.config/hypr/conf/layers.conf

# Default plugins in use
source = ~/.config/hypr/conf/plugins.conf

# Sections End #
general {
    gaps_in = 2
    gaps_out = 0
    border_size = 2
    # col.active_border = $act_border $act_border_2 45deg
    # col.inactive_border = $inac_border $inac_border_2 45deg
    col.active_border = $act_border
    col.inactive_border = $inac_border
    layout = dwindle
    allow_tearing = yes
    resize_on_border = yes
    hover_icon_on_border = true
    snap {
        enabled = true
        window_gap = 10
        monitor_gap = 10
        border_overlap = false
    }
}

decoration {

    rounding = 0
    rounding_power = 4
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0
    dim_inactive = true
    dim_strength = 0.1
    dim_special = 0.2
    dim_around = 0.6

    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
        xray = false
        noise = 0.02
        contrast = 1
        brightness = 0.6
        vibrancy = 0.8
        vibrancy_darkness = 1
        special = true
        popups = false
        ignore_opacity = true
    }
    shadow {
        enabled = true
        range = 10
        render_power = 2
        sharp = false
        ignore_window = true
        color = rgba(3,3,3,0.8)
        color_inactive = rgba(133, 133, 133, 0.1)
        offset = 1, 1
        scale = 1.0
    }
}

animations {
    # https://cubic-bezier.com/
    # https://easings.net
    # https://https://www.cssportal.com/css-cubic-bezier-generator/
    $time_spent=1.5 # wrongly defined as speed SPEED

    enabled = true
    first_launch_animation = true

	bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = linear, 1, 1, 1, 1
    bezier = Cubic, 0.1, 0.1, 0.1, 1
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    bezier = ease-in-out, 0.17, 0.67, 0.83, 0.67
    bezier = ease-in, 0.17, 0.67, 0.83, 0.67
    bezier = ease-out, 0.42, 0, 1, 1
    bezier = easeInOutSine, 0.37, 0, 0.63, 1
    bezier = easeInSine, 0.12, 0, 0.39, 0
    bezier = easeOutSine, 0.61, 1, 0.88, 1

    # animation = NAME, ONOFF, SPEED, CURVE [,STYLE]
    animation = windowsIn, 1, $time_spent, easeInOutSine, gnomed
    animation = windowsOut, 1, $time_spent, easeInOutSine, gnomed

    animation = border, 1, $time_spent, easeInOutSine
    animation = borderangle, 1, 30, easeInOutSine, loop

    animation = workspacesIn, 1, $time_spent, easeInOutSine, slidefade 80%
    animation = workspacesOut, 1, $time_spent, easeInOutSine, slidefade 80%

    animation = specialWorkspaceIn, 1, $time_spent, easeInOutSine, slidevert
    animation = specialWorkspaceOut, 1, $time_spent, easeInOutSine, slidevert

    animation = layersIn, 1, $time_spent, easeInOutSine, popin
    animation = layersOut, 1, $time_spent, easeInOutSine, popin

}

input {
    kb_layout = br
    kb_variant = abnt2
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 2
    focus_on_close = 1
    touchpad {
        natural_scroll = no
    }
    sensitivity = 0
    accel_profile = flat
    emulate_discrete_scroll	= 2
}

gestures {
    workspace_swipe = on
}

group {
    col.border_active = $group_act
    col.border_inactive = $group_inac
    col.border_locked_active = $group_lk_act
    col.border_locked_inactive = $group_lk_inac
    group_on_movetoworkspace = false
    merge_groups_on_groupbar = true

	groupbar {
	    enabled = true
	    height = 20
	    font_size = 11
	    stacked = false
	    col.active = $group_t_act
	    col.inactive = $group_t_inac
	    col.locked_active = $group_t_lk_act
	    col.locked_inactive = $group_t_lk_inac
	}

}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    always_follow_on_dnd = true
    layers_hog_keyboard_focus = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    enable_swallow = true
    swallow_regex = ^(waterfox-fetch.sh|firefox-dev.sh|kitty|allacritty|Alacritty|gnome-terminal|ptyxis|ghostty|distrobox|.AppImage|epiphany|chrome|chromium|brave|firefox|waterfox|librewolf)$
    focus_on_activate = false
    vfr = 1
    font_family = 'Inter Variable'
    splash_font_family = 'Inter Variable'
    col.splash = rgba(160, 186, 241, 1)
    background_color = rgba(8, 10, 11, 1)
    allow_session_lock_restore = true
}

binds {
     workspace_back_and_forth = 1
     allow_workspace_cycles = 1
     workspace_center_on = 1
     window_direction_monitor_fallback = true
}

xwayland {
    enabled = true
    use_nearest_neighbor = true
    force_zero_scaling = true
}

opengl {
	nvidia_anti_flicker = true
}

render {
   explicit_sync = 2
   explicit_sync_kms = 2
   direct_scanout = 2
   expand_undersized_textures = true
   xp_mode = false
   ctm_animation = 2
   cm_fs_passthrough = true
   cm_enabled = true
}

cursor {
	no_hardware_cursors = true
	use_cpu_buffer = 2
	enable_hyprcursor = true
	persistent_warps = true
	warp_on_change_workspace = 1
	#warp_on_toggle_special = 1
	default_monitor = $priMon
    sync_gsettings_theme = false
    warp_back_after_non_mouse_input = false
    # added for testing 2025-02-16
    no_warps = true
    persistent_warps = true
    hide_on_key_press = true
    hide_on_touch = true
    warp_back_after_non_mouse_input = true

}

ecosystem {
	no_update_news = false
}

# Sections End #

device {
    name = steelseries-steelseries-rival-3
    sensitivity = -0.5
    name = sino-wealth-gaming-kb--keyboard
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    allow_small_split = true
    special_scale_factor = 0.945
    mfact = 0.55

    new_status = slave
    new_on_top = false
    new_on_active = none

    orientation = left
    inherit_fullscreen = true
    slave_count_for_center_master = 3

    smart_resizing = true
    drop_at_cursor = true
}


Config File: /home/coop/.config/hypr/conf/preferences.conf: Read Succeeded
# My variables
# Running with hyprctl dispatch -- exec avoids https://github.com/Alexays/Waybar/issues/3302
# Autostarting with nwg-drawer -r or nwggrid-server keeps nwg-drawer or nwggrid in memory since Hyprland
# starts making it a bit faster to show, but it won't allow to different configurations
# Base
# Monitors
$mon0=eDP-1
$mon1=HDMI-A-1
$mon2=DP-1
$priMon=$mon1
$secMon=$mon0

# Base dirs
$conf_dir=$HOME/.config/hypr
$scripts=$conf_dir/scripts
$wallpapers_path=$HOME/Imagens/Walpapers
$appimages=$HOME/Applications

# Plugins related
$hyprbars_icon_size=18

# Misc
$xauthority_path=$XDG_RUNTIME_DIR/.hyprland.auth
$electron_knightmare=--enable-features=UseOzonePlatform --ozone-platform=wayland

# Initializers
$hyprexec=hyprctl dispatch -- exec
$uwsmexec=uwsm app --
#default Initializer
$executioner=$uwsmexec

# Mod key
$mainMod=SUPER

# Defaults
$fileManager=nautilus
$termEditor=micro
$musicPlayer=flatpak run com.github.taiko2k.tauonmb

# Terminal emulators
$ghostty=$appimages/ghostty.AppImage --theme="Ayu Mirage" --gtk-titlebar=false --shell-integration-features=true --cursor-style="block" --background-opacity=0.95 --window-decoration=false
$kitty=kitty --config $conf_dir/kitty/kitty.conf
$alacritty=alacritty
$ptyxis=ptyxis --standalone
$cosmicterm=cosmic-term
$screenRecorder=wf-recorder
$defaultTerminal=$ghostty

# UTILITIES
# Status bar
$waybarTheme=sharp
$waybar=waybar --bar $waybarTheme --config $conf_dir/waybar/$waybarTheme.jsonc --style $conf_dir/waybar/$waybarTheme.css
$status_bar=$waybar

# Notification daemon
$notification_daemon=swaync --config $conf_dir/swaync/config.json --style $conf_dir/swaync/sharp.css

# Launchers
$launcher=nwg-drawer -open
$launcher_server=nwg-drawer -r -nocats -nofs -k -ovl -s $conf_dir/nwg/drawer-sharp.css -closebtn right -fm $fileManager -wm hyprland -pbpoweroff "systemctl poweroff -i" -pblock "loginctl lock-session" -pbreboot "systemctl reboot -i" -pbexit "loginctl terminate-session $XDG_SESSION_ID"
$nwggrid=nwggrid -c $conf_dir/nwg/grid.css
$nwggrid_server=nwggrid-server -wm hyprland -n 5 -o 0.7 -layer-shell-layer OVERLAY -layer-shell-exclusive-zone auto

# Disk management
$automounter=udiskie --menu-update-workaround --menu-checkbox-workaround --automount --notify --smart-tray --file-manager "$fileManager" --terminal "$defaultTerminal"

# Password Manager (Bitwarden, Enpass etc)
$passwdManager=/opt/enpass/Enpass -minimise


Config File: /home/coop/.config/hypr/conf/colors.conf: Read Succeeded
# color names https://www.color-hex.com/color-names.html
# lilac https://www.color-hex.com/color-palette/5811
# charcoal https://www.color-hex.com/color/36454f
#
# Colors
source = ~/.config/hypr/conf/palette.conf

# Main borders
$act_border =  rgba(1A2862ff)
$act_border_2 =  rgba(334E95ff)
$inac_border = rgba(0C122Aff)
$inac_border_2 = rgba(0E1836ff)

# Shadows
$default_shadow = rgba(1a1a1aee)

# Group borders
$group_act = rgba(ff443300)
$group_inac = rgba(6600dd55)
$group_lk_act = rgba(ffff0000)
$group_lk_inac = rgba(dd00dd55)

# Group tabs ??
$group_t_act = rgba(ff443300)
$group_t_inac = rgba(6600dd55)
$group_t_lk_act = rgba(ffff0000)
$group_t_lk_inac = rgba(dd00dd55)

# Hyprbars
$hyprbar_bg = rgba(0A0D1Daa) #rgba(6, 8, 21, 1)
$hyprbar_txt = rgba(8ea4e588)
$hyprbar_close = rgba(f0808088)
$hyprbar_min = rgba(bcd5d688)
$hyprbar_max = rgba(32C74788)
$hyprbar_move = rgba(0a0a1dff)

# Misc
$yellow = rgba(FDBB40ff)
$blue = rgba(32C747ff)
$red = rgba(FC5753ff)
$black  = rgba(000000ff)
$blackish = rgba(121c24ff)
$white = rgba(f8f8ffff)
$clockm = rgba(141, 168, 231, 1)
$clockh = rgba(115, 133, 179, 1)
$clocks = rgba(72, 92, 163, 1)
$current_date = rgba(160, 186, 241, 1)
$border = rgba(ab78f3ff)
$backgd = rgba(151229ff)
$foregd = rgba(f8f8ffff)
$lilack = rgba(e6d7ffff)
$whiteish = rgba(f6f5f4ff)
$whitegray = rgba(dedddaff)
$whitegrayer = rgba(a9a9caff)
$cosmiccobalt = rgba(2e2d88ff)
$darkslateblue = rgba(483d8bff)
$cadetgrey = rgba(91a3b0ff)
$bluedefrance = rgba(318ce7ff)
$lavender = rgba(bf94e4ff)
$lightslateblue	= rgba(8470ffff)

# Lockscreen
$shape_border =  rgba(141, 168, 231, 0.5)
$shape_bg = rgba(10, 10, 29, 0.7)
$text_color = rgba(157, 198, 234, 1)

# General
$gaps_in = 0
$gaps_out = 0
$border_size = 1
$gen_active_border = $act_border $act_border_2 45deg
$gen_inactive_border = $inac_border $inac_border_2 45deg
$gen_active_border = $act_border
$gen_inactive_border = $inac_border
# Snap
$window_gap = 10
$monitor_gap = 10
# Decoration
$dec_rounding = 8
$dec_active_opacity = 1.0
$dec_inactive_opacity = 1.0
$dec_fullscreen_opacity = 1.0
$dec_dim_strength = 0.2
$dec_dim_special = 0.1
$dec_dim_around = 0.4
# blur
$blur_size = 3
$blur_passes = 1
$blur_noise = 0.02
$blur_contrast = 0.9
$blur_brightness = 0.9
$blur_vibrancy = 0.2
$blur_vibrancy_darkness = 0.1
# shadow
$shadow_range = 10
$shadow_render_power = 2
$shadow_color = rgba(33,33,33,0.5)
$shadow_color_inactive = rgba(133,133,133,0.5)
$shadow_offset = [1,1]
# Misc
$misc_font_family = 'Inter Variable'
$misc_splash_font_family = 'Inter Variable'
$misc_col_splash = rgba(160, 186, 241, 1)
$misc_bg_color = rgba(6, 8, 21, 1)
# Group
$grp_border_active = $group_act
$grp_border_inactive = $group_inac
$grp_border_locked_active = $group_lk_act
$grp_border_locked_inactive = $group_lk_inac
# groupbar
$gbar_height = 20
$gbar_font_size = 9
$gbar_active = $group_t_act
$gbar_inactive = $group_t_inac
$gbar_locked_active = $group_t_lk_act
$gbar_locked_inactive = $group_t_lk_inac


Config File: /home/coop/.config/hypr/conf/palette.conf: Read Succeeded
$mainbackground = rgb(29, 19, 70)
$secondarybackground = rgb(29, 22, 79)
$mainforeground = rgb(63, 70, 157)
$secondaryforeground = rgb(77, 95, 171)
$brightext = rgb(81, 101, 197)
$vividtext = rgb(67, 79, 255)
$alternatetext = rgb(119, 67, 219)
$borderlight = rgb(81, 101, 197)
$borderbright = rgb(128, 185, 229)
$alternatebackground = rgb(20, 10, 60)
$lighttext = rgb(109, 151, 221)
$peachy = rgb(242, 97, 63)
$shadow = rgb(33, 24, 85)
$floating = rgb(45, 30, 82)
$solo = rgb(22, 37, 111)
$nothing = rgb(45, 44, 131)
$maincritical = rgb(207, 34, 50)
$secondarycritical = rgb(238, 67, 76)
$rose = rgb(255, 220, 222)
$darkrose = rgb(233, 119, 119)
$darkpink = rgb(185, 139, 149)
$darkerpink = rgb(171, 106, 151)
$darkred = rgb(119, 8, 15)
$mainred = rgb(193, 18, 31)
$darkerred = rgb(107, 34, 50)
$limegreen = rgb(0, 246, 0)
$vividpurple = rgb(119, 67, 219)
$primarycritical = rgb(230, 55, 55)
$quarternarycritical = rgb(193, 18, 31)
$lightcritical = rgb(231, 148, 141)
$defaultbackground = rgb(10, 10, 29)
$primarybackground = rgb(6, 8, 21)
$secondarybackground = rgb(8, 10, 11)
$tertiarybackground = rgb(12, 12, 42)
$quarternarybackground = rgb(14, 14, 54)
$defaulttext = rgb(26, 26, 98)
$primarytext = rgb(44, 52, 160)
$secondarytext = rgb(141, 168, 231)
$tertiarytext = rgb(160, 186, 241)
$quarternarytext = rgb(130, 157, 218)
$newtext = rgb(58, 99, 160)
$bluetext = rgb(11, 47, 105)
$lilac = rgb(81, 81, 216)
$greenish = rgb(68, 137, 141)
$greenishiser = rgb(98, 152, 173)
$attention = rgb(51, 28, 55)
$greenlight = rgb(15, 115, 15)
$discharging = rgb(141, 43, 84)
$focused = rgb(72, 125, 192)
$onscreen = rgb(85, 120, 219)
$persistent = rgb(44, 52, 160)
$buttonhover = rgb(130, 130, 218)
$coffee = rgb(74, 73, 71)
$cappuccino = rgb(215, 211, 191)
$retroblueone = rgb(0, 92, 120)
$pessego = rgb(242, 97, 63)
$laranja = rgb(253, 139, 81)
$abobora = rgb(203, 96, 64)
$blue-shadow = rgb(22, 29, 111)
$almost-brown = rgb(200, 76, 5)
$night-blue = rgb(15, 4, 76)
$deep-blue = rgb(7, 2, 38)
$space-blue = rgb(5, 0, 25)
$teal = rgb(0, 153, 144)
$lime = rgb(225, 255, 187)
$pastel-teal = rgb(77, 161, 169)
$mint = rgb(121, 215, 190)
$navy = rgb(33, 53, 85)
$pastel-navy = rgb(62, 88, 121)
$vivid-navy = rgb(0, 26, 110)
$pastel-vivid-navy = rgb(7, 71, 153)
$bright-blue = rgb(1, 204, 255)
$brighter-blue = rgb(117, 209, 255)
$light-blue = rgb(174, 203, 250)
$bblue = rgb(53, 132, 228)
$vintage-red = rgb(201, 104, 104)
$vintage-yellow = rgb(250, 223, 161)
$vintage-beige = rgb(216, 210, 194)
$cream = rgb(255, 244, 234)
$creamtwo = rgb(250, 247, 240)
$warm-dirt = rgb(177, 116, 87)
$warm-cream = rgb(242, 229, 191)
$light-soil = rgb(154, 126, 111)
$soil = rgb(84, 71, 63)
$dark-soil = rgb(74, 73, 71)
$vintage-teal = rgb(126, 172, 181)
$dark-vintage-teal = rgb(37, 113, 128)
$vintage-blue = rgb(71, 147, 175)
$orange = rgb(253, 139, 81)
$pumpkin = rgb(203, 96, 64)
$warm-yellow = rgb(255, 196, 112)
$warm-peach = rgb(221, 87, 70)
$maroon = rgb(139, 50, 44)
$dark-maroon = rgb(61, 3, 1)
$darker-maroon = rgb(151, 49, 49)
$darkest-maroon = rgb(128, 61, 59)
$marron = rgb(72, 30, 20)
$almost-black = rgb(50, 44, 43)
$peachy = rgb(242, 97, 63)
$red-marron = rgb(155, 57, 34)
$bright-blue = rgb(1, 204, 255)
$brighter-blue = rgb(117, 209, 255)
$light-blue = rgb(174, 203, 250)
$bblue = rgb(53, 132, 228)
$workspacebutton = rgb(157, 198, 234)


Config File: /home/coop/.config/hypr/conf/autostart.conf: Read Succeeded
# Auto-starts / Must-haves

# Session/authentication
exec-once = uwsm app -s b -t service -- gnome-keyring-daemon --start --components=secrets
exec-once = uwsm app -s b -t service -- hash dbus-update-activation-environment 2>/dev/null &
exec-once = uwsm app -s b -t service -- /usr/libexec/flatpak-session-helper
exec-once = uwsm app -s b -t service -- systemctl --user import-environment
exec-once = uwsm app -s b -t service -- /home/coop/.config/hypr/scripts/polkit-gnome-authentication-agent-1 &
exec-once = uwsm app -s b -t service -- dbus-update-activation-environment --systemd --all

# Usability
exec-once = uwsm app -s a -- $status_bar
exec-once = uwsm app -s b -t service -- $notification_daemon
exec-once = uwsm app -s b -t service -- $launcher_server
exec-once = uwsm app -s b -t service -- $nwggrid_server

# Appearance / Feel
exec-once = uwsm app -s a -t service -- hypridle
exec-once = uwsm app -s a -t service -- hyprpaper
exec-once = uwsm app -s a -- waypaper --backend hyprpaper --restore --random --fill fill --folder $wallpapers_path
exec-once = uwsm app -s a -t service -- hyprdim --strength 0.5 --duration 100 --fade 150 --bezier "cubic-bezier(0.83, 0, 0.17, 1)"
exec-once = uwsm app -s a -t service -- hyprsunset --temperature 4500
exec-once = uwsm app -s a -t service -- ~/.config/hypr/scripts/nwg-hud.sh

# Needed for ProtonVPN
exec-once = uwsm app -s a -- nm-applet --indicator

# Some tray apps
exec-once = uwsm app -s a -- $automounter
exec-once = uwsm app -s a -- blueman-tray
exec-once = uwsm app -s a -- kdeconnect-indicator

# Password manager
exec-once = uwsm app -s a -- $passwdManager


Config File: /home/coop/.config/hypr/conf/monitors.conf: Read Succeeded
# monitor = ,preffered,auto,1
monitor= $priMon, 1920x1080@74.99, 0x0, 1.0
monitor= $secMon, 1920x1080@120.21300, 1920x0, 1.0


Config File: /home/coop/.config/hypr/conf/keybinds.conf: Read Succeeded
# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
# Default keybinds
# Flags for binds
# l -> locked, will also work when an input inhibitor (e.g. a lockscreen) is active.
# r -> release, will trigger on release of a key.
# c -> click, will trigger on release of a key or button as long as the mouse cursor stays inside input:drag_threshold.
# g -> drag, will trigger on release of a key or button as long as the mouse cursor moves outside input:drag_threshold.
# o -> longPress, will trigger on long press of a key.
# e -> repeat, will repeat when held.
# n -> non-consuming, key/mouse events will be passed to the active window in addition to triggering the dispatcher.
# m -> mouse, see below.
# t -> transparent, cannot be shadowed by other binds.
# i -> ignore mods, will ignore modifiers.
# s -> separate, will arbitrarily combine keys between each mod/key, see [Keysym combos](#keysym-combos) above.
# d -> has description, will allow you to write a description for your bind.
# p -> bypasses the app's requests to inhibit keybinds.
#
bindd = $mainMod SHIFT ALT CTRL, END, Exits Hyprland without asking, exec, uwsm stop
# bindd = $mainMod SHIFT ALT CTRL, END, Exits Hyprland by terminating the user sessions, exec, loginctl terminate-user ""
bindd = $mainMod, RETURN, Opens your $defaultTerminal terminal, exec, $defaultTerminal
bindd = $mainMod ALT, RETURN, Opens Kitty terminal, exec, $kitty
bindd = $mainMod SHIFT, RETURN, Opens Alacritty terminal, exec, $alacritty
bindd = $mainMod CTRL, RETURN, Opens Ghostty terminal, exec, $ghostty
bindd = $mainMod CTRL ALT, F5, Restarts waybar, exec, killall -SIGUSR2 waybar
bindd = $mainMod, E, Opens your file manager, exec, $fileManager
bindd = $mainMod, F, Opens your file manager, exec, cosmic-files
# bindd = $mainMod, Q, To close not kill the active window, killactive,
bindd = $mainMod, F4, To close not kill the active window, killactive,
bindd = $mainMod, M, To maximize the active window, fullscreenstate, 1 1

# To call the app launcher Gnome-like style
binddr = $mainMod, SUPER_L, Runs your app launcher, execr, uwsm app -s a -- nwg-drawer -open
binddr = $mainMod, X, Runs your app launcher, execr, uwsm app -s a -- $nwggrid
#binddo = , mouse:275, Runs your app launcher, execr, uwsm app -s a -- $nwggrid

# Toggles hyprbars
# binddr = $mainMod ALT, B, Toggles hyprbars on, exec, hyprctl plugin load /usr/lib64/hyprland/libhyprbars.so
# binddr = $mainMod CTRL, B, Toggles hyprbars off, exec, hyprctl plugin unload /usr/lib64/hyprland/libhyprbars.so
# bindd = , mouse:275, Mouse toggles on hyprbars, exec, hyprctl plugin load /usr/lib64/hyprland/libhyprbars.so
# bindd = , mouse:276, Mouse toggles off hyprbars, exec, hyprctl plugin unload /usr/lib64/hyprland/libhyprbars.so
binddr = $mainMod, SLASH, Toggles hyprbars, exec, hyprctl plugin load /usr/lib64/hyprland/libhyprbars.so
binddr = $mainMod, BACKSLASH, Toggles hyprbars, exec, hyprctl plugin unload /usr/lib64/hyprland/libhyprbars.so
# slash code 97
# backslash code 94

# Screen capture
# Screenshot with cosmic screenshot tool
bindd = , PRINT, Screen capture without annotation, exec, uwsm app -- ~/.config/hypr/scripts/screen_capture.sh quick
bindd = ALT, PRINT, Screen capture with annotation, exec, uwsm app -- ~/.config/hypr/scripts/screen_capture.sh
bindd = CTRL, PRINT, Window capture with annotation, exec, uwsm app -- ~/.config/hypr/scripts/screen_capture.sh window
bindd = SHIFT, PRINT, Region capture with annotation, exec, uwsm app -- ~/.config/hypr/scripts/screen_capture.sh region
bindd = $mainMod CTRL, PRINT, Region capture without annotation, exec, uwsm app -- ~/.config/hypr/scripts/screen_capture.sh quick
bindd = $mainMod SHIFT, PRINT, Region capture without annotation, exec, uwsm app -- ~/.config/hypr/scripts/screen_capture.sh

# Window behavior manipulation
# Window handling
bindd = $mainMod SHIFT, P, Pins the window making it visible in all workspaces, pin
bindd = $mainMod, SPACE, Toggles between floating and tiling mode, togglefloating,
bindd = $mainMod, D, Puts window in pseudo tiling mode, pseudo, # dwindle
bindd = $mainMod SHIFT, D, Toggles the split (top/side) of the current window, togglesplit, # dwindle

# Move focus with arrow keys
#bind = $mainMod, left, movewindow, l
#bind = $mainMod, right, movewindow, r
#bind = $mainMod, up, movewindow, u
#bind = $mainMod, down, movewindow, d
# Move focus with mainMod + arrow keys
bindde = $mainMod CTRL SHIFT, left, Move focus to the left, movefocus, l
bindde = $mainMod CTRL SHIFT, right, Move focus to the right, movefocus, r
bindde = $mainMod CTRL SHIFT, up, Move focus upwards, movefocus, u
bindde = $mainMod CTRL SHIFT, down, Move focus downwards, movefocus, d

# Grouping
bindd = $mainMod, G, Toggles the current active window into a group, togglegroup
bindd = $mainMod SHIFT, G, Moves the active window into a group in a specified direction, moveintogroup
bindd = $mainMod CTRL, G, Moves the active window out of a group, moveoutofgroup
bindd = $mainMod ALT, G, Switches to the next window in a group, changegroupactive

# Lockscreen
bindd = $mainMod, L, Activates the lockscreen, exec, $lockScreenCmd

# Switch workspaces with mainMod + [0-9]
binddr = $mainMod, 1, Switch to workspace 1, workspace, 1
binddr = $mainMod, 2, Switch to workspace 2, workspace, 2
binddr = $mainMod, 3, Switch to workspace 3, workspace, 3
binddr = $mainMod, 4, Switch to workspace 4, workspace, 4
binddr = $mainMod, 5, Switch to workspace 5, workspace, 5
binddr = $mainMod, 6, Switch to workspace 6, workspace, 6
binddr = $mainMod, 7, Switch to workspace 7, workspace, 7
binddr = $mainMod, 8, Switch to workspace 8, workspace, 8
binddr = $mainMod, 9, Switch to workspace 9, workspace, 9
binddr = $mainMod, 0, Switch to workspace 10, workspace, 10

binddr = $mainMod ALT, 0, Switch to workspace Gaming, workspace, name:Gaming
binddr = $mainMod SHIFT ALT, 0, Switch to workspace Gaming, movetoworkspace, name:Gaming

# NWG-HUD for the workspaces
# binddr = $mainMod, 1, Switch to workspace 1, exec, $scripts/nwg-hud.sh -m " WS 1"
# binddr = $mainMod, 2, Switch to workspace 2, exec, $scripts/nwg-hud.sh -m " WS 2"
# binddr = $mainMod, 3, Switch to workspace 3, exec, $scripts/nwg-hud.sh -m " WS 3"
# binddr = $mainMod, 4, Switch to workspace 4, exec, $scripts/nwg-hud.sh -m " WS 4"
# binddr = $mainMod, 5, Switch to workspace 5, exec, $scripts/nwg-hud.sh -m " WS 5"
# binddr = $mainMod, 6, Switch to workspace 6, exec, $scripts/nwg-hud.sh -m " WS 6"
# binddr = $mainMod, 7, Switch to workspace 7, exec, $scripts/nwg-hud.sh -m " WS 7"
# binddr = $mainMod, 8, Switch to workspace 8, exec, $scripts/nwg-hud.sh -m " WS 8"
# binddr = $mainMod, 9, Switch to workspace 9, exec, $scripts/nwg-hud.sh -m " WS 9"
# binddr = $mainMod, 0, Switch to workspace 10, exec, $scripts/nwg-hud.sh -m " WS 10"

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bindd = $mainMod SHIFT, 1, Send active window to workspace 1 silently, movetoworkspacesilent, 1
bindd = $mainMod SHIFT, 2, Send active window to workspace 2 silently, movetoworkspacesilent, 2
bindd = $mainMod SHIFT, 3, Send active window to workspace 3 silently, movetoworkspacesilent, 3
bindd = $mainMod SHIFT, 4, Send active window to workspace 4 silently, movetoworkspacesilent, 4
bindd = $mainMod SHIFT, 5, Send active window to workspace 5 silently, movetoworkspacesilent, 5
bindd = $mainMod SHIFT, 6, Send active window to workspace 6 silently, movetoworkspacesilent, 6
bindd = $mainMod SHIFT, 7, Send active window to workspace 7 silently, movetoworkspacesilent, 7
bindd = $mainMod SHIFT, 8, Send active window to workspace 8 silently, movetoworkspacesilent, 8
bindd = $mainMod SHIFT, 9, Send active window to workspace 9 silently, movetoworkspacesilent, 9
bindd = $mainMod SHIFT, 0, Send active window to workspace 10 silently, movetoworkspacesilent, 10

bindd = $mainMod CTRL, 1, Throws all unfocused windows on the current workspace to the given workspace, plugin:xtd:throwunfocused
bindd = $mainMod CTRL, 2, Kinda inverse of throwunfocused. Bring all windows from a given workspace to the current one., plugin:xtd:bringallfrom
bindd = $mainMod CTRL, 3, Close all unfocused windows on the current workspace., plugin:xtd:closeunfocused

# Special workspaces (scratchpads)
bindd = $mainMod, F12, Call special workspace Magic, togglespecialworkspace, magic
bindd = $mainMod SHIFT, F12, Move active window to special workspace Magic, movetoworkspacesilent, special:magic
bindd = $mainMod, F1, Call special workspace Nebula, togglespecialworkspace, nebula
bindd = $mainMod ALT SHIFT, F1, Move active window to special workspace Magic, movetoworkspacesilent, special:nebula
bindd = $mainMod, F2, Call special workspace Magic, togglespecialworkspace, scratchpad
bindd = $mainMod ALT SHIFT, F2, Move active window to special workspace Magic, movetoworkspacesilent, special:scratchpad

# Scroll through existing workspaces with mainMod + scroll
bindd = $mainMod, mouse_down, Scroll through workspaces incrementally, workspace, e+1
bindd = $mainMod, mouse_up, Scroll through workspaces decrementally,workspace, e-1

# Next / Previous Workspace with Page Up and Page Down
bindd = $mainMod, PAGE_DOWN, Scroll through workspaces incrementally, workspace, e+1
bindd = $mainMod, PAGE_UP, Scroll through workspaces decrementally, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
binddm = $mainMod, mouse:272, Move window with $mainMod + left mouse button, movewindow
binddm = $mainMod, mouse:273, Resize window with $mainMod + right mouse button, resizewindow

# Move the whole workspace
bindd = $mainMod ALT, period, Move current workspace to another monitor incrementally, movecurrentworkspacetomonitor, +1
bindd = $mainMod ALT, comma, Move current workspace to another monitor decrementally, movecurrentworkspacetomonitor, -1

# Minimized Windows
bindd = $mainMod, S, Minimize/foregrounds a single window, togglespecialworkspace, minimized
bindd = $mainMod, S, Minimize/foregrounds a single window, movetoworkspace, +0
bindd = $mainMod, S, Minimize/foregrounds a single window, togglespecialworkspace, minimized
bindd = $mainMod, S, Minimize/foregrounds a single window, movetoworkspace, special:minimized
bindd = $mainMod, S, Minimize/foregrounds a single window, togglespecialworkspace, minimized

# trigger when the switch is toggled
bindl = , switch:[Lid Switch], exec, $lockScreenCmd
# trigger when the switch is turning on
#bindl = , switch:on:[Lid Switch], exec, hyprctl keyword monitor "eDP-1, disable"
# trigger when the switch is turning off
#bindl = , switch:off:[Lid Switch], exec, hyprctl keyword monitor "eDP-1, 2560x1600, 0x0, 1"

# Two steps to move a window to another workspace
# useful for number of workspaces greater than 10
# bind = $mainMod, W, submap, MoveToWorkspace
# submap = MoveToWorkspace
# binde = , escape, submap, MoveToWorkspace
# binde = , movetoworkspace
# submap = reset
# Activate keyboard window resize mode
# https://wiki.hyprland.org/0.45.0/Configuring/Binds/#submaps
bindd = $mainMod ALT, SPACE, Activates window resizing mode, submap, Resize mode
submap = Resize mode
bindde = , right, Resize to the right (resizing mode), resizeactive, 15 0
bindde = , left, Resize to the left (resizing mode), resizeactive, -15 0
bindde = , up, Resize upwards (resizing mode), resizeactive, 0 -15
bindde = , down, Resize downwards (resizing mode), resizeactive, 0 15
bindde = , l, Resize to the right (resizing mode), resizeactive, 15 0
bindde = , h, Resize to the left (resizing mode), resizeactive, -15 0
bindde = , k, Resize upwards (resizing mode), resizeactive, 0 -15
bindde = , j, Resize downwards (resizing mode), resizeactive, 0 15
bindd = , escape, Ends window resizing mode, submap, reset
submap = reset

# bindde = CTRL SHIFT ALT, left, Resize window to the left,resizeactive, -10 0
# bindde = CTRL SHIFT ALT, right, Resize window to the right, resizeactive, 10 0
# bindde = CTRL SHIFT ALT, up, Resize window upwards, resizeactive, 0 -10
# bindde = CTRL SHIFT ALT, down, Resize window downwards, resizeactive, 0 10
# bindde = CTRL SHIFT ALT, l, Resize window to the left,resizeactive, -10 0
# bindde = CTRL SHIFT ALT, h, Resize window to the right, resizeactive, 10 0
# bindde = CTRL SHIFT ALT, k, Resize window upwards, resizeactive, 0 -10
# bindde = CTRL SHIFT ALT, j, Resize window downwards, resizeactive, 0 10

# Special keys, multimedia etc
bindde = , XF86AudioRaiseVolume, Increases volume gradually by 5%, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindde = , XF86AudioLowerVolume, Decreases volume gradually by 5%, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindde = , XF86AudioMute, Mute audio output, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bindde = , XF86AudioMicMute, Mute audio input, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindde = , XF86MonBrightnessDown, Increases brightness gradually by 5%, exec, brightnessctl set 5%-
bindde = , XF86MonBrightnessUp, Decreases brightness gradually by 5%, exec, brightnessctl set 5%+
bindde = , XF86AudioPlay, Music player toggle play/pause,exec, playerctl play-pause
bindde = , XF86AudioNext, Music player next track, exec, playerctl next
bindde = , XF86AudioPrev, Music player previous track, exec, playerctl previous
bindde = , XF86audiostop, Music player stop, exec, playerctl stop


source = $conf_dir/conf/fullscreen.conf


Config File: /home/coop/.config/hypr/conf/fullscreen.conf: Read Succeeded
# Fullscreenstate sets the focused window’s fullscreen mode and the one 
# sent to the client	internal client, where internal and client can be 
# -1 - current
# 0 - none
# 1 - maximize
# 2 - fullscreen
# 3 - maximize and fullscreen
bindd = $mainMod, F, Puts window in fullscreen mode keeping shape, fullscreenstate, 0 1
bind = $mainMod SHIFT, F, fullscreenstate, 0 0
bindd = $mainMod, Z, Puts window in fullscreen mode not keeping shape, fullscreenstate, 0 2
# bind = $mainMod, Ç, fullscreenstate, -1 3

# fullscreen state: internal client, where internal and client can be 
#                 -1 - current
#                 0 - none
#                 1 - maximize
#                 2 - fullscreen
#                 3 - maximize and fullscreen
# fullscreen: 
#                 0 - fullscreen (takes your entire screen)
#                 1 - maximize (keeps gaps and bar(s))

# Maximizes and fullscreen to the whole screen
bindd = $mainMod ALT, 1, Fullscreen 0, fullscreen, 0

# Maximizes the window, respects gaps and status bars; fullscreen with F11 limited to the window's occupied area
bindd = $mainMod ALT, 2, Fullscreen 1, fullscreen, 1

# No initial visual changes; resets everything or does nothing
bindd = $mainMod ALT, 3, Fullscreen State -1 -1, fullscreenstate, -1 -1

# No initial visual changes; resets everything probably or does nothing
bindd = $mainMod ALT, 4, Fullscreen State -1 0, fullscreenstate, -1 0

# No initial visual changes; locks fullscreen to the tile
bindd = $mainMod ALT, 5, Fullscreen State -1 1, fullscreenstate, -1 1

# Maximizes and fullscreens to its tile; locks fullscreen to the tile
bindd = $mainMod ALT, 6, Fullscreen State -1 2, fullscreenstate, -1 2

# Maximizes and fullscreens to its tile; locks fullscreen to the tile
bindd = $mainMod ALT, 7, Fullscreen State -1 3, fullscreenstate, -1 3

# Restore normal behavior it seems
bindd = $mainMod ALT, 8, Fullscreen State 0 0, fullscreenstate, 0 0

# No initial visual changes; keeps normal behavior
bindd = $mainMod ALT, 9, Fullscreen State 0 -1, fullscreenstate, 0 -1

# No initial visual changes; locks fullscreen to the tile
bindd = $mainMod ALT, 0, Fullscreen State 0 1, fullscreenstate, 0 1

# Maximizes and fullscreens the window to its tile, respects gaps and status bars; fullscreen with F11 fills the tile
bindd = $mainMod ALT, F1, Fullscreen State 0 2, fullscreenstate, 0 2

# Maximizes and fullscreens the window to its current tile, respects gaps and status bars; fullscreen with F11 fills the current tile
bindd = $mainMod ALT, F2, Fullscreen State 0 3 , fullscreenstate, 0 3

# Maximizes the window to current workspace, respects gaps and status bars; fullscreen with F11 limited to the window's occupied area
bindd = $mainMod ALT, F3, Fullscreen State 1 0, fullscreenstate, 1 0

# Maximizes the window to current workspace, respects gaps and status bars; fullscreen with F11 fills the whole screen
bindd = $mainMod ALT, F4, Fullscreen State 1 1, fullscreenstate, 1 1

# Maximizes the window and fullscreens it to current workspace, respects gaps and status bars; fullscreen with F11 limited to the window's occupied area
bindd = $mainMod ALT, F5, Fullscreen State 1 2, fullscreenstate, 1 2

# Maximizes the window and fullscreens it to current workspace, respects gaps and status bars; fullscreen with F11 limited to the window's occupied area
bindd = $mainMod ALT, F6, Fullscreen State 1 3, fullscreenstate, 1 3

# Maximizes the window to its current workpace, respects gaps and status bars; fullscreen with F11 fills the whole screen
bindd = $mainMod ALT, F7, Fullscreen State 1 1, fullscreenstate, 1 1

Config File: /home/coop/.config/hypr/conf/windows.conf: Read Succeeded
# Windows rules
# regex reference https://github.com/google/re2/wiki/Syntax
# windowrule = float, class:.*
windowrule = suppressevent maximize, class:.* # You'll probably like this.
windowrule = persistentsize, class:.* # to keep last window size used on floating windows
#windowrule = opacity 1 override 1 override 1, class:.* # forcefully disabling transparency

# Persistency test
windowrule = float, class:^(com.system76.CosmicFiles)$
#windowrule = persistentsize, class:^(com.system76.CosmicFiles)$
windowrule = float, title:^(.*Hyprshot.*)$
#windowrule = persistentsize, title:^(.*Hyprshot.*)$
windowrule = float, class:mpv
#windowrule = persistentsize, class:mpv
windowrule = center, class:^(org.gnome.Nautilus)(.*)$
#windowrule = persistentsize, class:^(org.gnome.Nautilus)(.*)$

# Hyprbars
# windowrule = plugin:hyprbars:nobar, focus:0
# windowrule = plugin:hyprbars:nobar, initialClass:^(com.system76.CosmicAppletTime)(.*)$

# Xwaylandvideobridge (if installed) KDE sollution for screensharing
windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrule = noanim, class:^(xwaylandvideobridge)$
windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrule = noblur, class:^(xwaylandvideobridge)$

# Clipboard app (com.github.hluk.copyq)
windowrule = tag +ClipboardManager, class:^(com.github.hluk.copyq)$
windowrule = float, class:^(com.github.hluk.copyq)$
windowrule = size 65% 65%, class:^(com.github.hluk.copyq)$
windowrule = bordercolor rgba(ff0000ff) rgba(aa0000ff), class:^(com.github.hluk.copyq)$
windowrule = dimaround, class:^(com.github.hluk.copyq)$
windowrule = animation popin, class:^(com.github.hluk.copyq)$

# Browsers related
windowrule = opaque, title:^(LibreWolf|Brave|Firefox|Floorp|Vivaldi|Chromium|Chrome)(.*)$
windowrule = noblur, title:^(LibreWolf|Brave|Firefox|Floorp|Vivaldi|Chromium|Chrome)(.*)$
windowrule = float, title:^(LibreWolf|Brave|Firefox|Floorp|Vivaldi|Chromium|Chrome)(.*)$, tag +browser +navegador
windowrule = opacity 1.0 override 1.0 override 1.0 override, title:^(LibreWolf|Brave|Firefox|Floorp|Vivaldi|Chromium|Chrome)(.*)$

# For Vivaldi's first window (profile selection)
windowrule = float, class:^(.*vivaldi.*)
#windowrule = persistentsize, class:^(.*vivaldi.*)
windowrule = size 57.8125% 68.51851851851852%, class:^(.*vivaldi.*)
windowrule = center center, class:^(.*vivaldi.*)

# Some defaults
windowrule = tile, class:^(.*office.*)$
windowrule = float, title:^(Junction)(.*)$
windowrule = float, class:(org.gnome.Calculator)$
# windowrule = float, class:^(org.gnome.Calendar)$
windowrule = center, class:(org.gnome.Calculator)$
windowrule = center, class:^(Enpass), title:^(Enpass)$
# windowrule = center, class:^(org.gnome.Calendar)$
# windowrule = size 1600 900, class:^(org.gnome.Calendar)$
windowrule = size 90% 90%, class:^(Enpass), title:^(Enpass)$
windowrule = opacity 1 override 1, class:^(Alacritty|org.contourterminal.Contour|org.gnome.Ptyxis|kitty|gnome-terminal)(.*)$
windowrule = float, class:^(nm-connection-editor)(.*)$
windowrule = size 51.666666667% 64.444444444%, class:^(nm-connection-editor)(.*)$
windowrule = rounding 5, class:^(nm-connection-editor)(.*)$
windowrule = float, class:^(nwg-displays)$
windowrule = size 1280 720, class:^(nwg-displays)$
windowrule = minsize 1 1, class:^(nwg-displays)$
windowrule = float, class:^(org.freedesktop.GnomeAbrt)$

# ProtonVPN
windowrule = float, class:^(protonvpn-app)$,title:^(Proton VPN)
windowrule = size 400 1020, class:^(protonvpn-app)$,title:^(Proton VPN)
windowrule = minsize 1 1, class:^(protonvpn-app)$,title:^(Proton VPN)
windowrule = move 1515 45, class:^(protonvpn-app)$,title:^(Proton VPN)

# Dialogs / Popups
windowrule = float, class:^()$,title:^(Save File)$
windowrule = float, class:^()$,title:^(Open File)$
windowrule = float, title:^(Open File|Open image|Abrir Arquivo|Abrir imagem)(.*)$
windowrule = size 1280 720, title:^(Open File|Open image|Abrir Arquivo|Abrir imagem)(.*)$
windowrule = center center, title:^(Open File|Open image|Abrir Arquivo|Abrir imagem)(.*)$
windowrule = float, title:^(Select a File)(.*)$
windowrule = float, title:^(Pick a file)(.*)$
windowrule = float, title:^(Choose wallpaper)(.*)$
windowrule = float, title:^(Open Folder)(.*)$
windowrule = float, title:^(Save As)(.*)$
windowrule = float, title:^(Library)(.*)$
windowrule = float, title:^(Password Required)(.*)$
windowrule = float, title:^(Compress folders|Compactar pastas)(.*)$
windowrule = size 430 900, class:^(org.gnome.Nautilus)$,title:^(Abrir arquivo)$
windowrule = float, class:^(org.gnome.Nautilus)$,title:^(Propriedades|Properties)(.*)$
windowrule = size 31.7% 47.6%, class:^(org.gnome.Nautilus)$,title:^(Propriedades|Properties)(.*)$
windowrule = dimaround, class:^(org.gnome.Nautilus)$,title:^(Propriedades|Properties)(.*)$
windowrule = float, class:(.*)(Dialog)$ # For COSMIC Dialogs

windowrule = float, class:^(fsearch)$
windowrule = size 77% 77%, class:^(fsearch)$
windowrule = dimaround, class:^(fsearch)$

# Not working for Enpass. Doesn't matter if it's in docked mode or not.
# It always opens in the wrong place
windowrule = float, title:^(Enpass Assistant)(.*)$
windowrule = move 65% 25%, title:^(Enpass Assistant)(.*)$
windowrule = bordercolor rgb(FFFF00), title:^(Enpass Assistant)(.*)$
windowrule = bordersize 4, title:^(Enpass Assistant)(.*)$

# Float Necessary Windows
windowrule = float, class:^(Rofi|Wofi)$
windowrule = float, class:^(org.pulseaudio.pavucontrol|cosmic|com.system76.CosmicSettings)$
windowrule = float, initialClass:^(com.system76.CosmicSettings)$
windowrule = float, class:^()$,title:^(Picture in picture)$
windowrule = float, class:^(zen|LibreWolf|Firefox|)$,title:^(Picture-in-Picture)$
windowrule = float, class:^(blueman-manager)$
windowrule = float, class:^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
windowrule = float, class:^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$
windowrule = float, class:^(CachyOSHello)$
windowrule = float, class:^(zenity)$
windowrule = float, class:^(org.gnome.)(.*)$
windowrule = float, class:^(gnome-)(.*)$
windowrule = float, title:^(Junction)(.*)$
windowrule = float, title:^(NVIDIA Settings)(.*)$
windowrule = float, title:^(Sobre|About|Preferences|Preferências)(.*)$
windowrule = center, class:^(org.gnome.)(.*)$
windowrule = center, class:^(gnome-)(.*)$
windowrule = center, title:^(NVIDIA Settings)(.*)$
windowrule = center, title:^(Sobre|About|Preferences|Preferências)(.*)$
windowrule = size 1280 720, title:^(NVIDIA Settings)(.*)$
windowrule = size 720 auto, title:^(Sobre|About|Preferences|Preferências)(.*)$
windowrule = size 720 80%, title:^(flatpak)(.*)$
windowrule = float, class:^(org.gnome.Nautilus)(.*)$
windowrule = center, class:^(org.gnome.Nautilus)(.*)$
windowrule = size 1600 900, class:^(org.gnome.Nautilus)(.*)$
windowrule = size 430 900, class:^(org.gnome.Nautilus)$, title:^(Preferências)$
windowrule = float, class:^(udiskie)$
windowrule = center center, class:^(udiskie)$

# Steam, Nvidia etc
windowrule = workspace 5, class:^(steam|heroic)(.*)$, title:^(Steam|Heroic Games Launcher)(.*)$
windowrule = float, class:^(steam|heroic)(.*)$, title:^(Steam|Heroic Games Launcher)(.*)$
windowrule = minsize 1450 1005, class:^(steam)(.*)$, title:^(Steam)(.*)$
windowrule = center center, class:^(steam|heroic)(.*)$, title:^(Steam|Heroic Games Launcher)(.*)$
windowrule = workspace 5, class:^(steam)(.*)$, title:^(Friends List)$
windowrule = workspace 5, class:^(steam)(.*)$, title:^(Sign in to Steam)$
windowrule = workspace 5, class:^(steam)(.*)$, title:^(Steam Dialog)$
windowrule = workspace 5, class:^(steam)(.*)$, title:^(Special Offers)$
windowrule = float, class:^(steam)(.*)$
windowrule = float, class:^(steam)(.*)$, title:^(Sign in to Steam)(.*)$
windowrule = float, class:^()$, title:^(Steam - Self Updater)$
windowrule = float, class:^(steam)(.*)$, title:^(Friends List)$
windowrule = float, class:^(steam)(.*)$, title:^(Steam Settings)$
windowrule = float, class:^(steam)(.*)$, title:^(Steam Dialog)$
windowrule = center center, class:(steam)$, title:^(Sign in to Steam)(.*)$
windowrule = center center, class:(steam)$, title:^(Special Offers)(.*)
windowrule = center center, class:(steam)$, title:^(Steam Dialog)(.*)
windowrule = minsize 1 1, title:^()$, class:^(steam)(.*)$
windowrule = forcergbx, title:^(), class:^(steam)(.*)$
windowrule = move 1311 70, class:^(steam)(.*)$, title:^(Friends List)(.*)$
windowrule = size 24% 90%, class:^(steam)(.*)$, title:^(Friends List)$
windowrule = size 33.75% 26.574074074074073%, class:^(steam)(.*)$, title:^(Steam Dialog)$
windowrule = minsize 33.75% 26.574074074074073%, class:^(steam)(.*)$, title:^(Steam Dialog)$
windowrule = maxsize 33.75% 26.574074074074073%, class:^(steam)(.*)$, title:^(Steam Dialog)$
windowrule = float, class:^(steam)(.*)$, title:^(Launcher)(.*)$
windowrule = size 1200 800, class:^(steam)(.*)$, title:^(Launcher)(.*)$
windowrule = center, class:^(steam)(.*)$, title:^(Launcher)(.*)$
windowrule = center center, class:^(steam)(.*)$, title:^(Steam Settings)(.*)$
windowrule = minsize 1280 720, class:^(steam)(.*)$, title:^(Steam Settings)(.*)$
windowrule = maxsize 1280 720, class:^(steam)(.*)$, title:^(Steam Settings)(.*)$
windowrule = minsize 36.77% 76.85%, class:^(steam)(.*)$, title:^(Special Offers)(.*)$
windowrule = opacity 1 override 1 override 1, class:^(steam)(.*)$, title:^(Steam Settings)(.*)$

# For gaming
windowrule = fullscreen, class:^steam_app\d+$
windowrule = content game, class:^steam_app\d+$
windowrule = monitor $priMon, class:^steam_app_\d+$
windowrule = workspace name:Gaming, class:^steam_app_\d+$
windowrule = immediate, class:^(gamescope)$
windowrule = forcergbx, title:^(), class:^(steam_app_\d+)$
windowrule = immediate, class:^steam_app_\d+$
windowrule = fullscreen, class:^(gamescope)$
windowrule = monitor $priMon, class:^(gamescope)$
windowrule = workspace name:Gaming, class:^(gamescope)$
windowrule = fullscreen, initialClass:^(Godot)$
windowrule = content game, initialClass:^(Godot)$
windowrule = monitor $priMon, initialClass:^(Godot)$
windowrule = workspace name:Gaming, initialClass:^(Godot)$
windowrule = immediate, initialClass:^(Godot)$

# based on ML4W, Pavucontrol floating
windowrule = float, class:(.*org.pulseaudio.pavucontrol.*)$
windowrule = size 700 600, class:(.*org.pulseaudio.pavucontrol.*)$
windowrule = center, class:(.*org.pulseaudio.pavucontrol.*)$
windowrule = pin, class:(.*org.pulseaudio.pavucontrol.*)$

# Smart gaps (vaxry)
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding 0, floating:0, onworkspace:f[1]

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# TESTS
# These next two rules may interefere with various menus e.g. electron apps
#windowrule = minsize 1280 720, floating:1, focusHistoryID:2, onworkspace:w[fv1-10]
#windowrule = maxsize 1600 900, floating:1, focusHistoryID:2, onworkspace:w[fv1-10]
windowrule = fullscreen, class:^(com.example.flash)$
windowrule = size 100% 100%, class:^(com.example.flash)$

windowrule = float,class:(com.ml4w.calendar)
#windowrule = move 50%-w-816 66,class:(com.ml4w.calendar)
windowrule = move 761 34, class:(com.ml4w.calendar)
windowrule = pin, class:(com.ml4w.calendar)
windowrule = size 400 400,class:(com.ml4w.calendar)

windowrule = float, class:(org.gnome.Calendar)
# windowrule = persistentsize, class:(org.gnome.Calendar)
# windowrule = move 100%-w-10 0, class:(org.gnome.Calendar)
windowrule = move 50%-w-580 35, class:(org.gnome.Calendar)
windowrule = pin, class:(org.gnome.Calendar)
windowrule = size 580 600, class:(org.gnome.Calendar)

# These next two rules deal with chromium based and electron apps menu blur/opacity glitches
windowrule = opacity 1 override 1, focusHistoryID:2, onworkspace:w[fv1-10]
windowrule = noblur 1 override 1, focusHistoryID:2, onworkspace:w[fv1-10]
windowrule = noshadow 1 override 1, focusHistoryID:2, onworkspace:w[fv1-10]


Config File: /home/coop/.config/hypr/conf/workspaces.conf: Read Succeeded
# Workspaces rules
workspace = 1, persistent:true, monitor:$priMon, default:true
workspace = 2, persistent:true, monitor:$priMon
workspace = 3, persistent:true, monitor:$priMon
workspace = 4, persistent:true, monitor:$priMon
workspace = 5, persistent:true, monitor:$priMon
workspace = 6, persistent:true, monitor:$secMon, default:true
workspace = 7, persistent:true, monitor:$secMon
workspace = 8, persistent:true, monitor:$secMon
workspace = 9, persistent:true, monitor:$secMon
workspace = 10, persistent:true, monitor:$secMon
workspace = name:Gaming, persistent:false, monitor:$priMon, defaultName:Gaming, f[1], default:false, gapsin:0, gapsout:0, bordersize:0, border:false, shadow:false, rouding:false, decorate:false
workspace = 11, monitor:$priMon, persistent:false, defaultName:Games, f[0], default:false, gapsin:0, gapsout:0, bordersize:0, border:false, shadow:false, rouding:false, decorate:false

# Specials / Scratchpads
workspace = special:nebula, gapsin:2, gapsout:10, border:true, rounding:false, bordersize:1, decorate:true, bordercolor rgb(255,255,255)
workspace = special:magic, gapsin:2, gapsout:10, border:true, rounding:false, bordersize:1, decorate:true
workspace = special:scratchpad, on-create-empty:alacritty
workspace = special:minimized, border:false, decorate:false
workspace = special:Backups, gapsin:2, gapsout:4, border:true, rounding:false, bordersize:4, decorate:true, bordercolor rgb(55,55,255)

# Smart gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0


Config File: /home/coop/.config/hypr/conf/layers.conf: Read Succeeded
# # Animation types available for layers
# https://wiki.hyprland.org/Configuring/Animations/#animation-tree
#
# ######## Layer rules ########
layerrule = noanim, selection

layerrule = blur, logout_dialog
layerrule = animation fade, logout_dialog

layerrule = blur, gtk-layer-shell
layerrule = ignorezero, gtk-layer-shell

layerrule = blur, launcher

layerrule = blur, ^(swaync-control-center)$
layerrule = animation fade, ^(swaync-control-center)$

layerrule = blur, hyprpaper
layerrule = animation fade, hyprpaper

layerrule = blur, nwg-drawer
layerrule = animation slide, nwg-drawer

layerrule = blur, nwg-hud
layerrule = animation slide, nwg-hud

layerrule = blur, nwggrid
layerrule = animation slide, nwggrid

layerrule = blur, waybar
layerrule = animation slide, waybar


Config File: /home/coop/.config/hypr/conf/plugins.conf: Read Succeeded
# plugin = /usr/lib64/hyprland/libhyprbars.so
# plugin = /usr/lib64/hyprland/libborders-plus-plus.so
plugin = /usr/lib64/hyprland/libxtra-dispatchers.so
plugin {

    hyprbars {
        # https://www.reddit.com/r/hyprland/comments/1cyaz4u/i_like_hyprbars_thats_all/
        bar_height = 32
        bar_title_enabled = true
        # bar_color = $hyprbar_bg
        # bar_color = $hyprbar_bg
        bar_color = $hyprbar_bg
        col.text = $hyprbar_txt
        bar_text_size = 12
        bar_text_font = 'Inter Variable'
        bar_text_align = center
        bar_buttons_alignment = left
        bar_padding = 10
        bar_button_padding = 10
        bar_precedence_over_border = true
        bar_part_of_window = true
        bar_blur = true

        hyprbars-button = $hyprbar_close, $hyprbars_icon_size, 󰧞 , hyprctl dispatch killactive
        hyprbars-button = $hyprbar_max, $hyprbars_icon_size, 󰧞 , hyprctl dispatch fullscreen 1
        hyprbars-button = $hyprbar_min, $hyprbars_icon_size, 󰧞 , hyprctl dispatch movetoworkspacesilent special:minimized
        hyprbars-button = $hyprbar_move, $hyprbars_icon_size, 󰐃 , hyprctl dispatch pin
        hyprbars-button = $hyprbar_move, $hyprbars_icon_size,   , hyprctl dispatch togglefloating
        # hyprbars-button = $hyprbar_bg, $hyprbars_icon_size,  , hyprctl dispatch movewindow mon:$secMon
        # hyprbars-button = $hyprbar_bg, $hyprbars_icon_size,  , hyprctl dispatch movewindow mon:$priMon
        # hyprbars-button = $hyprbar_bg, $hyprbars_icon_size,  , hyprctl dispatch movetoworkspace special:nebula
        # hyprbars-button = $hyprbar_bg, $hyprbars_icon_size,  , hyprctl dispatch movetoworkspace special:magic
        hyprbars-button = $hyprbar_move, $hyprbars_icon_size, 󱣴 , hyprctl dispatch fullscreenstate 0 1
        hyprbars-button = $hyprbar_move, $hyprbars_icon_size,  , hyprctl dispatch fullscreen 0
        # hyprbars-button = $hyprbar_bg, $hyprbars_icon_size, 󱂬 , hyprctl dispatch pseudo
        hyprbars-button = $hyprbar_bg, $hyprbars_icon_size,  , hyprctl plugin unload /usr/lib64/hyprland/libhyprbars.so

        #   1   
    }
    borders-plus-plus {
        add_borders = 2 # 0 - 9

        # you can add up to 9 borders
        col.border_1 = rgba(12, 12, 42, 1)
        col.border_2 = rgba(160, 186, 241, 1)
        col.border_3 = $inac_border
        col.border_4 = $inac_border_2

        # -1 means "default" as in the one defined in general:border_size
        border_size_1 = 1
        border_size_2 = 1
        border_size_3 = -1
        border_size_4 = -1

        # makes outer edges match rounding of the parent. Turn on / off to better understand. Default = on.
        natural_rounding = on
    }
}

======Config-End========


```

</details>

### Description

Dynamic text are not working anymore, onl Sample Text is shown, even if copying and pasting the examples from the wiki.

```
[ERR] Config has errors:
Config error in file /home/coop/.config/hypr/hyprlock.conf at line 108: Invalid expression type: supported +, -, *, /
Config error in file /home/coop/.config/hypr/hyprlock.conf at line 121: Invalid expression type: supported +, -, *, /
Config error in file /home/coop/.config/hypr/hyprlock.conf at line 136: Invalid expression type: supported +, -, *, /
Config error in file /home/coop/.config/hypr/hyprlock.conf at line 151: Invalid expression type: supported +, -, *, /
Config error in file /home/coop/.config/hypr/hyprlock.conf at line 165: Invalid expression type: supported +, -, *, /
```

### How to reproduce

Use a file with a text field containing a dynamic command like one int he wiki.

**Comment by vaxerski** [comment]
bug in hyprlang 0.6.2 fixed in 0.6.3

**Comment by msmafra** [comment]
Ok. I'll wait for the repo to be updated. Thx.

**Comment by GeodeArc** [comment]
> bug in hyprlang 0.6.2 fixed in 0.6.3

Still an issue for me.
paru -Q hyprlang
hyprlang 0.6.3-1

hyprlock
Hyprlock version v0.8.2
[ERR] Config has errors:
Config error in file /home/dg/.config/hypr/hyprlock.conf at line 131: Invalid expression type: supported +, -, *, /

**Comment by msmafra** [comment]
For me it was solved minutes after since the COPR (external repo) was already updated to 0.6.3. As soon as I updated it and logged out and back in it worked.

**Comment by GeodeArc** [comment]
> For me it was solved minutes after since the COPR (external repo) was already updated to 0.6.3. As soon as I updated it and logged out and back in it worked.

Most commands now work for me as well. The issue is now (apparently) that commands with currly brackets {} seem to no longer work since this release, and worked previously. Might create a separate issue, but its not a big deal for me, and ive already found a (kinda jank) workaround.
