### ISSUE TITLE
Scaling issue in hyprlock after logging in

### ISSUE THREAD

**Issue by etwodev** [hyprwm/hyprlock#837]
### Regression?

No

### Hyprlock Info and Version

Hyprlock version v0.9.0
<details> <summary>Hyprlock config</summary>

```sh
general {
    ignore_empty_input = true
}

background {
    monitor = DP-1
    path = ~/.config/assets/wp/02.jpg
    blur_passes = 3
}

background {
    monitor = DP-2
    path = ~/.config/assets/wp/03.jpg
    blur_passes = 3
}

input-field {
    monitor =
    size = 200, 40
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.4
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.25)
    font_color = $foreground
    fade_on_empty = false
    rounding = 12
    check_color = rgb(204, 136, 34)
    placeholder_text = <i><span foreground="##cdd6f4">Input Password...</span></i>
    hide_input = false
    position = 0, -160
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "[TIME] $(date +%H:%M:%S.%3N)"
    color = rgba(242, 243, 244, 0.85)
    font_size = 10
    font_family = JetBrainsMono NF
    position = 0, -120
    halign = center
    valign = center
}

# Profile Picture
image {
    monitor =
    path = ~/.config/assets/profile_icon.webp
    size = 500
    position = 0, 110
    opacity = 0.9
    border_color = rgba(0, 0, 0, 0)
    halign = center
    valign = center
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.50.1 built from branch  at commit 4e242d086e20b32951fdc0ebcbfb4d41b5be8dcc  ([gha] Nix: update inputs).
Date: Sat Jul 19 21:37:06 2025
Tag: v0.50.1, commits: 6291
built against:
 aquamarine 0.9.2
 hyprlang 0.6.3
 hyprutils 0.8.1
 hyprcursor 0.1.12
 hyprgraphics 0.1.5


no flags were set


System Information:
System name: Linux
Node name: arch-bagan
Release: 6.15.8-2-cachyos
Version: #1 SMP PREEMPT_DYNAMIC Fri, 25 Jul 2025 19:00:03 +0000


GPU information: 
00:02.0 Display controller [0380]: Intel Corporation Raptor Lake-S GT1 [UHD Graphics 770] [8086:a780] (rev 04)
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD104 [GeForce RTX 4070 Ti] [10de:2782] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  575.64.05  Release Build  (notroot@)  Fri Jul 25 19:12:04 UTC 2025


os-release: NAME="CachyOS Linux"
PRETTY_NAME="CachyOS"
ID=cachyos
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://cachyos.org/"
DOCUMENTATION_URL="https://wiki.cachyos.org/"
SUPPORT_URL="https://discuss.cachyos.org/"
BUG_REPORT_URL="https://github.com/cachyos"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=cachyos


plugins:
```

</details>

### Description

After entering my password into hyprlock and entering hyprland, there is obvious scaling issues. Improperly rotated monitor, windows scaled to vertical. These correct themselves after a second but very annoying. This does not happen on my other monitor setups, this is a fresh install. 

### How to reproduce

1. Using the provided config, enter hyprlock
2. Enter your password
3. Assuming similar monitor configuration, the rescaling issue should be present

### Crash reports, logs, images, videos

Monitors Configuration:
```sh
# https://wiki.hyprland.org/0.45.0/Configuring/Monitors/
monitor = DP-1,3440x1440@174.96,0x0,1
monitor = DP-2,1920x1080@239.99,3440x0,1,transform,1
```

Hyprctl Monitors:
```sh
Monitor DP-1 (ID 0):
	3440x1440@174.96201 at 0x0
	description: Samsung Electric Company Odyssey G8 H1AK500000
	make: Samsung Electric Company
	model: Odyssey G8
	serial: H1AK500000
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	directScanoutTo: 0
	disabled: false
	currentFormat: XRGB8888
	mirrorOf: none
	availableModes: 3440x1440@59.96Hz 3440x1440@174.96Hz 3440x1440@119.96Hz 2560x1440@174.97Hz 2560x1440@120.00Hz 2560x1440@59.95Hz 1920x1080@174.92Hz 1920x1080@120.00Hz 1920x1080@119.88Hz 1920x1080@59.94Hz 1680x1050@59.95Hz 1600x900@60.00Hz 1280x1024@60.02Hz 1440x900@59.89Hz 1280x800@59.81Hz 1280x720@60.00Hz 1280x720@59.94Hz 1024x768@60.00Hz 800x600@60.32Hz 720x480@59.94Hz 640x480@59.94Hz 

Monitor DP-2 (ID 1):
	1920x1080@239.98900 at 3440x0
	description: HP Inc. OMEN 27s CNC3112161
	make: HP Inc.
	model: OMEN 27s
	serial: CNC3112161
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 1
	focused: no
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	directScanoutTo: 0
	disabled: false
	currentFormat: XRGB8888
	mirrorOf: none
	availableModes: 1920x1080@60.00Hz 1920x1080@239.99Hz 1920x1080@164.92Hz 1920x1080@143.98Hz 1920x1080@120.00Hz 1920x1080@119.88Hz 1920x1080@100.00Hz 1920x1080@74.97Hz 1920x1080@59.94Hz 1680x1050@59.95Hz 1600x900@60.00Hz 1280x1024@60.02Hz 1440x900@59.89Hz 1280x800@59.81Hz 1280x720@60.00Hz 1280x720@59.94Hz 1024x768@60.00Hz 800x600@60.32Hz 720x480@59.94Hz 640x480@59.94Hz 640x480@59.93Hz 
```

Video demo:

**Comment by etwodev** [comment]
Just as a note, if transform is removed, this scaling issue is no longer present.

**Comment by PaideiaDilemma** [comment]
Did you check -git?

**Comment by etwodev** [comment]
Yes, fixed.
Fixed with https://github.com/hyprwm/hyprlock/commit/1e5e62d6e31de0d2610ade4a424d4b696d137a78.
Hence, related to https://github.com/hyprwm/hyprlock/issues/824

**Comment by katzeprior** [comment]
> [@etwodev](https://github.com/etwodev) 0.9.1 was just release and will hopefully arrive soon at your distro.

I am running Hyprland 0.50.1 and hyprlock 0.9.1 and the stretching still occurs if I don't have any blur enabled but only after `reload_time` and `reload_cmd` part where it sets a new random wallpaper from a folder.
